// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1071520897;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__coaching_api__calibrate_imu_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "calibrate_imu",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_samples =
                <Vec<crate::api::coaching_api::ImuSample>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::coaching_api::calibrate_imu(api_samples))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__clear_reference_lap_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "clear_reference_lap",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::coaching_api::clear_reference_lap();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__create_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::types::SessionConfig>::sse_decode(&mut deserializer);
            let api_cue_config = <Option<crate::types::CueConfig>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::coaching_api::create_session(
                        api_config,
                        api_cue_config,
                    ))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__destroy_session_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "destroy_session",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::coaching_api::destroy_session();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__get_ml_features_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_ml_features",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::coaching_api::get_ml_features())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__coaching_api__has_reference_lap_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "has_reference_lap",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::coaching_api::has_reference_lap())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__list_analyzers_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_analyzers",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::coaching_api::list_analyzers())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__process_frame_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "process_frame",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_input = <crate::types::TelemetryInput>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(crate::api::coaching_api::process_frame(api_input))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__reset_lap_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "reset_lap",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::coaching_api::reset_lap();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__set_analysis_config_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_analysis_config",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::types::AnalysisConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::coaching_api::set_analysis_config(api_config);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__set_cue_config_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_cue_config",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_config = <crate::types::CueConfig>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::coaching_api::set_cue_config(api_config);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__coaching_api__set_reference_lap_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "set_reference_lap",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_frames = <Vec<crate::types::TelemetryInput>>::sse_decode(&mut deserializer);
            let api_lap_time_s = <f64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::coaching_api::set_reference_lap(api_frames, api_lap_time_s);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::types::AnalysisConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_speedIntegratedDistance = <bool>::sse_decode(deserializer);
        let mut var_centerlineProjection = <bool>::sse_decode(deserializer);
        let mut var_sectorTimer = <bool>::sse_decode(deserializer);
        let mut var_deltaT = <bool>::sse_decode(deserializer);
        let mut var_brakingGOnset = <bool>::sse_decode(deserializer);
        let mut var_cornerSpeed = <bool>::sse_decode(deserializer);
        let mut var_trailBraking = <bool>::sse_decode(deserializer);
        let mut var_jerkAnalysis = <bool>::sse_decode(deserializer);
        let mut var_speedDerivative = <bool>::sse_decode(deserializer);
        let mut var_frictionCircle = <bool>::sse_decode(deserializer);
        let mut var_combinedG = <bool>::sse_decode(deserializer);
        let mut var_headingMatching = <bool>::sse_decode(deserializer);
        let mut var_curvatureMatching = <bool>::sse_decode(deserializer);
        let mut var_energyDissipation = <bool>::sse_decode(deserializer);
        let mut var_brakingEfficiency = <bool>::sse_decode(deserializer);
        let mut var_throttleAnalysis = <bool>::sse_decode(deserializer);
        let mut var_brakePressure = <bool>::sse_decode(deserializer);
        return crate::types::AnalysisConfig {
            speed_integrated_distance: var_speedIntegratedDistance,
            centerline_projection: var_centerlineProjection,
            sector_timer: var_sectorTimer,
            delta_t: var_deltaT,
            braking_g_onset: var_brakingGOnset,
            corner_speed: var_cornerSpeed,
            trail_braking: var_trailBraking,
            jerk_analysis: var_jerkAnalysis,
            speed_derivative: var_speedDerivative,
            friction_circle: var_frictionCircle,
            combined_g: var_combinedG,
            heading_matching: var_headingMatching,
            curvature_matching: var_curvatureMatching,
            energy_dissipation: var_energyDissipation,
            braking_efficiency: var_brakingEfficiency,
            throttle_analysis: var_throttleAnalysis,
            brake_pressure: var_brakePressure,
        };
    }
}

impl SseDecode for crate::api::coaching_api::AnalyzerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_enabled = <bool>::sse_decode(deserializer);
        return crate::api::coaching_api::AnalyzerInfo {
            id: var_id,
            enabled: var_enabled,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::types::BrakingState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_isBraking = <bool>::sse_decode(deserializer);
        let mut var_brakingG = <f32>::sse_decode(deserializer);
        let mut var_distanceSinceOnset = <f32>::sse_decode(deserializer);
        let mut var_referenceOnsetDeltaM = <Option<f32>>::sse_decode(deserializer);
        return crate::types::BrakingState {
            is_braking: var_isBraking,
            braking_g: var_brakingG,
            distance_since_onset: var_distanceSinceOnset,
            reference_onset_delta_m: var_referenceOnsetDeltaM,
        };
    }
}

impl SseDecode for crate::types::CoachingCue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_cueType = <crate::types::CueType>::sse_decode(deserializer);
        let mut var_message = <String>::sse_decode(deserializer);
        let mut var_priority = <crate::types::CuePriority>::sse_decode(deserializer);
        let mut var_cornerNumber = <Option<u32>>::sse_decode(deserializer);
        let mut var_deltaSeconds = <Option<f64>>::sse_decode(deserializer);
        let mut var_distanceDeltaM = <Option<f64>>::sse_decode(deserializer);
        return crate::types::CoachingCue {
            cue_type: var_cueType,
            message: var_message,
            priority: var_priority,
            corner_number: var_cornerNumber,
            delta_seconds: var_deltaSeconds,
            distance_delta_m: var_distanceDeltaM,
        };
    }
}

impl SseDecode for crate::types::Corner {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_number = <u32>::sse_decode(deserializer);
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_entry = <crate::types::LatLng>::sse_decode(deserializer);
        let mut var_apex = <crate::types::LatLng>::sse_decode(deserializer);
        let mut var_exit = <crate::types::LatLng>::sse_decode(deserializer);
        return crate::types::Corner {
            number: var_number,
            name: var_name,
            entry: var_entry,
            apex: var_apex,
            exit: var_exit,
        };
    }
}

impl SseDecode for crate::types::CueConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_verbosity = <u8>::sse_decode(deserializer);
        let mut var_enableBrakingCues = <bool>::sse_decode(deserializer);
        let mut var_enableCornerSpeedCues = <bool>::sse_decode(deserializer);
        let mut var_enableDeltaTCues = <bool>::sse_decode(deserializer);
        let mut var_enableCoastingCues = <bool>::sse_decode(deserializer);
        let mut var_enableGripLimitCues = <bool>::sse_decode(deserializer);
        let mut var_enableTrailBrakingCues = <bool>::sse_decode(deserializer);
        let mut var_enableJerkCues = <bool>::sse_decode(deserializer);
        let mut var_deltaTThresholdS = <f64>::sse_decode(deserializer);
        let mut var_coastingThreshold = <f32>::sse_decode(deserializer);
        let mut var_overDrivingThreshold = <f32>::sse_decode(deserializer);
        let mut var_brakingDeltaThresholdM = <f32>::sse_decode(deserializer);
        let mut var_cornerSpeedThresholdKmh = <f32>::sse_decode(deserializer);
        let mut var_perCornerCooldownS = <f32>::sse_decode(deserializer);
        let mut var_perTypeCooldownS = <f32>::sse_decode(deserializer);
        return crate::types::CueConfig {
            verbosity: var_verbosity,
            enable_braking_cues: var_enableBrakingCues,
            enable_corner_speed_cues: var_enableCornerSpeedCues,
            enable_delta_t_cues: var_enableDeltaTCues,
            enable_coasting_cues: var_enableCoastingCues,
            enable_grip_limit_cues: var_enableGripLimitCues,
            enable_trail_braking_cues: var_enableTrailBrakingCues,
            enable_jerk_cues: var_enableJerkCues,
            delta_t_threshold_s: var_deltaTThresholdS,
            coasting_threshold: var_coastingThreshold,
            over_driving_threshold: var_overDrivingThreshold,
            braking_delta_threshold_m: var_brakingDeltaThresholdM,
            corner_speed_threshold_kmh: var_cornerSpeedThresholdKmh,
            per_corner_cooldown_s: var_perCornerCooldownS,
            per_type_cooldown_s: var_perTypeCooldownS,
        };
    }
}

impl SseDecode for crate::types::CuePriority {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::types::CuePriority::Low,
            1 => crate::types::CuePriority::Medium,
            2 => crate::types::CuePriority::High,
            3 => crate::types::CuePriority::Critical,
            _ => unreachable!("Invalid variant for CuePriority: {}", inner),
        };
    }
}

impl SseDecode for crate::types::CueType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::types::CueType::Braking,
            1 => crate::types::CueType::Throttle,
            2 => crate::types::CueType::Line,
            3 => crate::types::CueType::Speed,
            4 => crate::types::CueType::SectorTime,
            5 => crate::types::CueType::LapTime,
            6 => crate::types::CueType::GForce,
            7 => crate::types::CueType::General,
            8 => crate::types::CueType::Coasting,
            9 => crate::types::CueType::TrailBraking,
            10 => crate::types::CueType::GripUtilization,
            11 => crate::types::CueType::MlBraking,
            12 => crate::types::CueType::MlThrottle,
            _ => unreachable!("Invalid variant for CueType: {}", inner),
        };
    }
}

impl SseDecode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::types::FrameOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_trackDistanceM = <f64>::sse_decode(deserializer);
        let mut var_lapDistancePct = <f32>::sse_decode(deserializer);
        let mut var_deltaTSeconds = <f64>::sse_decode(deserializer);
        let mut var_deltaTTrend = <f32>::sse_decode(deserializer);
        let mut var_coachingCues = <Vec<crate::types::CoachingCue>>::sse_decode(deserializer);
        let mut var_frictionCircle = <crate::types::FrictionCircleState>::sse_decode(deserializer);
        let mut var_brakingState = <crate::types::BrakingState>::sse_decode(deserializer);
        let mut var_currentSector = <u32>::sse_decode(deserializer);
        let mut var_sectorDelta = <Option<f64>>::sse_decode(deserializer);
        let mut var_gripUtilization = <f32>::sse_decode(deserializer);
        return crate::types::FrameOutput {
            track_distance_m: var_trackDistanceM,
            lap_distance_pct: var_lapDistancePct,
            delta_t_seconds: var_deltaTSeconds,
            delta_t_trend: var_deltaTTrend,
            coaching_cues: var_coachingCues,
            friction_circle: var_frictionCircle,
            braking_state: var_brakingState,
            current_sector: var_currentSector,
            sector_delta: var_sectorDelta,
            grip_utilization: var_gripUtilization,
        };
    }
}

impl SseDecode for crate::types::FrictionCircleState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_gTotal = <f32>::sse_decode(deserializer);
        let mut var_gMax = <f32>::sse_decode(deserializer);
        let mut var_utilization = <f32>::sse_decode(deserializer);
        let mut var_isCoasting = <bool>::sse_decode(deserializer);
        let mut var_isTrailBraking = <bool>::sse_decode(deserializer);
        return crate::types::FrictionCircleState {
            g_total: var_gTotal,
            g_max: var_gMax,
            utilization: var_utilization,
            is_coasting: var_isCoasting,
            is_trail_braking: var_isTrailBraking,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::types::ImuBias {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_lateralG = <f32>::sse_decode(deserializer);
        let mut var_longitudinalG = <f32>::sse_decode(deserializer);
        let mut var_verticalG = <f32>::sse_decode(deserializer);
        let mut var_sampleCount = <u32>::sse_decode(deserializer);
        return crate::types::ImuBias {
            lateral_g: var_lateralG,
            longitudinal_g: var_longitudinalG,
            vertical_g: var_verticalG,
            sample_count: var_sampleCount,
        };
    }
}

impl SseDecode for crate::api::coaching_api::ImuSample {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_gLateral = <f32>::sse_decode(deserializer);
        let mut var_gLongitudinal = <f32>::sse_decode(deserializer);
        let mut var_gVertical = <f32>::sse_decode(deserializer);
        return crate::api::coaching_api::ImuSample {
            g_lateral: var_gLateral,
            g_longitudinal: var_gLongitudinal,
            g_vertical: var_gVertical,
        };
    }
}

impl SseDecode for crate::types::LatLng {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_lat = <f64>::sse_decode(deserializer);
        let mut var_lng = <f64>::sse_decode(deserializer);
        return crate::types::LatLng {
            lat: var_lat,
            lng: var_lng,
        };
    }
}

impl SseDecode for Vec<crate::api::coaching_api::AnalyzerInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::coaching_api::AnalyzerInfo>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::types::CoachingCue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::types::CoachingCue>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::types::Corner> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::types::Corner>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::coaching_api::ImuSample> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::coaching_api::ImuSample>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::types::LatLng> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::types::LatLng>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<f32>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::types::SectorSplit> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::types::SectorSplit>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::types::TelemetryInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::types::TelemetryInput>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::types::CueConfig> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::types::CueConfig>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<f64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::types::ImuBias> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::types::ImuBias>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u32>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::types::SectorSplit {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sectorNumber = <u32>::sse_decode(deserializer);
        let mut var_pointA = <crate::types::LatLng>::sse_decode(deserializer);
        let mut var_pointB = <crate::types::LatLng>::sse_decode(deserializer);
        return crate::types::SectorSplit {
            sector_number: var_sectorNumber,
            point_a: var_pointA,
            point_b: var_pointB,
        };
    }
}

impl SseDecode for crate::types::SessionConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_track = <crate::types::TrackConfig>::sse_decode(deserializer);
        let mut var_analysis = <crate::types::AnalysisConfig>::sse_decode(deserializer);
        let mut var_useMph = <bool>::sse_decode(deserializer);
        return crate::types::SessionConfig {
            track: var_track,
            analysis: var_analysis,
            use_mph: var_useMph,
        };
    }
}

impl SseDecode for crate::types::TelemetryInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_timestampMs = <u64>::sse_decode(deserializer);
        let mut var_latitude = <f64>::sse_decode(deserializer);
        let mut var_longitude = <f64>::sse_decode(deserializer);
        let mut var_speedKmh = <f32>::sse_decode(deserializer);
        let mut var_headingDeg = <f32>::sse_decode(deserializer);
        let mut var_altitudeM = <f32>::sse_decode(deserializer);
        let mut var_gLateral = <f32>::sse_decode(deserializer);
        let mut var_gLongitudinal = <f32>::sse_decode(deserializer);
        let mut var_gVertical = <f32>::sse_decode(deserializer);
        let mut var_satellites = <u8>::sse_decode(deserializer);
        let mut var_hdop = <f32>::sse_decode(deserializer);
        return crate::types::TelemetryInput {
            timestamp_ms: var_timestampMs,
            latitude: var_latitude,
            longitude: var_longitude,
            speed_kmh: var_speedKmh,
            heading_deg: var_headingDeg,
            altitude_m: var_altitudeM,
            g_lateral: var_gLateral,
            g_longitudinal: var_gLongitudinal,
            g_vertical: var_gVertical,
            satellites: var_satellites,
            hdop: var_hdop,
        };
    }
}

impl SseDecode for crate::types::TrackConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <String>::sse_decode(deserializer);
        let mut var_finishLineA = <crate::types::LatLng>::sse_decode(deserializer);
        let mut var_finishLineB = <crate::types::LatLng>::sse_decode(deserializer);
        let mut var_corners = <Vec<crate::types::Corner>>::sse_decode(deserializer);
        let mut var_sectorSplits = <Vec<crate::types::SectorSplit>>::sse_decode(deserializer);
        let mut var_centerline = <Vec<crate::types::LatLng>>::sse_decode(deserializer);
        let mut var_trackLengthM = <Option<f64>>::sse_decode(deserializer);
        return crate::types::TrackConfig {
            name: var_name,
            finish_line_a: var_finishLineA,
            finish_line_b: var_finishLineB,
            corners: var_corners,
            sector_splits: var_sectorSplits,
            centerline: var_centerline,
            track_length_m: var_trackLengthM,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__coaching_api__calibrate_imu_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__coaching_api__clear_reference_lap_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__coaching_api__create_session_impl(port, ptr, rust_vec_len, data_len),
        4 => {
            wire__crate__api__coaching_api__destroy_session_impl(port, ptr, rust_vec_len, data_len)
        }
        5 => {
            wire__crate__api__coaching_api__get_ml_features_impl(port, ptr, rust_vec_len, data_len)
        }
        7 => wire__crate__api__coaching_api__has_reference_lap_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        8 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__coaching_api__list_analyzers_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__coaching_api__process_frame_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__coaching_api__reset_lap_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__crate__api__coaching_api__set_analysis_config_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        13 => {
            wire__crate__api__coaching_api__set_cue_config_impl(port, ptr, rust_vec_len, data_len)
        }
        14 => wire__crate__api__coaching_api__set_reference_lap_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        6 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::AnalysisConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.speed_integrated_distance.into_into_dart().into_dart(),
            self.centerline_projection.into_into_dart().into_dart(),
            self.sector_timer.into_into_dart().into_dart(),
            self.delta_t.into_into_dart().into_dart(),
            self.braking_g_onset.into_into_dart().into_dart(),
            self.corner_speed.into_into_dart().into_dart(),
            self.trail_braking.into_into_dart().into_dart(),
            self.jerk_analysis.into_into_dart().into_dart(),
            self.speed_derivative.into_into_dart().into_dart(),
            self.friction_circle.into_into_dart().into_dart(),
            self.combined_g.into_into_dart().into_dart(),
            self.heading_matching.into_into_dart().into_dart(),
            self.curvature_matching.into_into_dart().into_dart(),
            self.energy_dissipation.into_into_dart().into_dart(),
            self.braking_efficiency.into_into_dart().into_dart(),
            self.throttle_analysis.into_into_dart().into_dart(),
            self.brake_pressure.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::AnalysisConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::AnalysisConfig>
    for crate::types::AnalysisConfig
{
    fn into_into_dart(self) -> crate::types::AnalysisConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::coaching_api::AnalyzerInfo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.enabled.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::coaching_api::AnalyzerInfo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::coaching_api::AnalyzerInfo>
    for crate::api::coaching_api::AnalyzerInfo
{
    fn into_into_dart(self) -> crate::api::coaching_api::AnalyzerInfo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::BrakingState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.is_braking.into_into_dart().into_dart(),
            self.braking_g.into_into_dart().into_dart(),
            self.distance_since_onset.into_into_dart().into_dart(),
            self.reference_onset_delta_m.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::BrakingState {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::BrakingState> for crate::types::BrakingState {
    fn into_into_dart(self) -> crate::types::BrakingState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::CoachingCue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.cue_type.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.priority.into_into_dart().into_dart(),
            self.corner_number.into_into_dart().into_dart(),
            self.delta_seconds.into_into_dart().into_dart(),
            self.distance_delta_m.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::CoachingCue {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::CoachingCue> for crate::types::CoachingCue {
    fn into_into_dart(self) -> crate::types::CoachingCue {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::Corner {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.number.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.entry.into_into_dart().into_dart(),
            self.apex.into_into_dart().into_dart(),
            self.exit.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::Corner {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::Corner> for crate::types::Corner {
    fn into_into_dart(self) -> crate::types::Corner {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::CueConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.verbosity.into_into_dart().into_dart(),
            self.enable_braking_cues.into_into_dart().into_dart(),
            self.enable_corner_speed_cues.into_into_dart().into_dart(),
            self.enable_delta_t_cues.into_into_dart().into_dart(),
            self.enable_coasting_cues.into_into_dart().into_dart(),
            self.enable_grip_limit_cues.into_into_dart().into_dart(),
            self.enable_trail_braking_cues.into_into_dart().into_dart(),
            self.enable_jerk_cues.into_into_dart().into_dart(),
            self.delta_t_threshold_s.into_into_dart().into_dart(),
            self.coasting_threshold.into_into_dart().into_dart(),
            self.over_driving_threshold.into_into_dart().into_dart(),
            self.braking_delta_threshold_m.into_into_dart().into_dart(),
            self.corner_speed_threshold_kmh.into_into_dart().into_dart(),
            self.per_corner_cooldown_s.into_into_dart().into_dart(),
            self.per_type_cooldown_s.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::CueConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::CueConfig> for crate::types::CueConfig {
    fn into_into_dart(self) -> crate::types::CueConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::CuePriority {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Low => 0.into_dart(),
            Self::Medium => 1.into_dart(),
            Self::High => 2.into_dart(),
            Self::Critical => 3.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::CuePriority {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::CuePriority> for crate::types::CuePriority {
    fn into_into_dart(self) -> crate::types::CuePriority {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::CueType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Braking => 0.into_dart(),
            Self::Throttle => 1.into_dart(),
            Self::Line => 2.into_dart(),
            Self::Speed => 3.into_dart(),
            Self::SectorTime => 4.into_dart(),
            Self::LapTime => 5.into_dart(),
            Self::GForce => 6.into_dart(),
            Self::General => 7.into_dart(),
            Self::Coasting => 8.into_dart(),
            Self::TrailBraking => 9.into_dart(),
            Self::GripUtilization => 10.into_dart(),
            Self::MlBraking => 11.into_dart(),
            Self::MlThrottle => 12.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::CueType {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::CueType> for crate::types::CueType {
    fn into_into_dart(self) -> crate::types::CueType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::FrameOutput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.track_distance_m.into_into_dart().into_dart(),
            self.lap_distance_pct.into_into_dart().into_dart(),
            self.delta_t_seconds.into_into_dart().into_dart(),
            self.delta_t_trend.into_into_dart().into_dart(),
            self.coaching_cues.into_into_dart().into_dart(),
            self.friction_circle.into_into_dart().into_dart(),
            self.braking_state.into_into_dart().into_dart(),
            self.current_sector.into_into_dart().into_dart(),
            self.sector_delta.into_into_dart().into_dart(),
            self.grip_utilization.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::FrameOutput {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::FrameOutput> for crate::types::FrameOutput {
    fn into_into_dart(self) -> crate::types::FrameOutput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::FrictionCircleState {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.g_total.into_into_dart().into_dart(),
            self.g_max.into_into_dart().into_dart(),
            self.utilization.into_into_dart().into_dart(),
            self.is_coasting.into_into_dart().into_dart(),
            self.is_trail_braking.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::types::FrictionCircleState
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::types::FrictionCircleState>
    for crate::types::FrictionCircleState
{
    fn into_into_dart(self) -> crate::types::FrictionCircleState {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::ImuBias {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.lateral_g.into_into_dart().into_dart(),
            self.longitudinal_g.into_into_dart().into_dart(),
            self.vertical_g.into_into_dart().into_dart(),
            self.sample_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::ImuBias {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::ImuBias> for crate::types::ImuBias {
    fn into_into_dart(self) -> crate::types::ImuBias {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::coaching_api::ImuSample {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.g_lateral.into_into_dart().into_dart(),
            self.g_longitudinal.into_into_dart().into_dart(),
            self.g_vertical.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::coaching_api::ImuSample
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::coaching_api::ImuSample>
    for crate::api::coaching_api::ImuSample
{
    fn into_into_dart(self) -> crate::api::coaching_api::ImuSample {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::LatLng {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.lat.into_into_dart().into_dart(),
            self.lng.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::LatLng {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::LatLng> for crate::types::LatLng {
    fn into_into_dart(self) -> crate::types::LatLng {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::SectorSplit {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.sector_number.into_into_dart().into_dart(),
            self.point_a.into_into_dart().into_dart(),
            self.point_b.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::SectorSplit {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::SectorSplit> for crate::types::SectorSplit {
    fn into_into_dart(self) -> crate::types::SectorSplit {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::SessionConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.track.into_into_dart().into_dart(),
            self.analysis.into_into_dart().into_dart(),
            self.use_mph.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::SessionConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::SessionConfig>
    for crate::types::SessionConfig
{
    fn into_into_dart(self) -> crate::types::SessionConfig {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::TelemetryInput {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.timestamp_ms.into_into_dart().into_dart(),
            self.latitude.into_into_dart().into_dart(),
            self.longitude.into_into_dart().into_dart(),
            self.speed_kmh.into_into_dart().into_dart(),
            self.heading_deg.into_into_dart().into_dart(),
            self.altitude_m.into_into_dart().into_dart(),
            self.g_lateral.into_into_dart().into_dart(),
            self.g_longitudinal.into_into_dart().into_dart(),
            self.g_vertical.into_into_dart().into_dart(),
            self.satellites.into_into_dart().into_dart(),
            self.hdop.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::TelemetryInput {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::TelemetryInput>
    for crate::types::TelemetryInput
{
    fn into_into_dart(self) -> crate::types::TelemetryInput {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::types::TrackConfig {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.finish_line_a.into_into_dart().into_dart(),
            self.finish_line_b.into_into_dart().into_dart(),
            self.corners.into_into_dart().into_dart(),
            self.sector_splits.into_into_dart().into_dart(),
            self.centerline.into_into_dart().into_dart(),
            self.track_length_m.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::types::TrackConfig {}
impl flutter_rust_bridge::IntoIntoDart<crate::types::TrackConfig> for crate::types::TrackConfig {
    fn into_into_dart(self) -> crate::types::TrackConfig {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::types::AnalysisConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.speed_integrated_distance, serializer);
        <bool>::sse_encode(self.centerline_projection, serializer);
        <bool>::sse_encode(self.sector_timer, serializer);
        <bool>::sse_encode(self.delta_t, serializer);
        <bool>::sse_encode(self.braking_g_onset, serializer);
        <bool>::sse_encode(self.corner_speed, serializer);
        <bool>::sse_encode(self.trail_braking, serializer);
        <bool>::sse_encode(self.jerk_analysis, serializer);
        <bool>::sse_encode(self.speed_derivative, serializer);
        <bool>::sse_encode(self.friction_circle, serializer);
        <bool>::sse_encode(self.combined_g, serializer);
        <bool>::sse_encode(self.heading_matching, serializer);
        <bool>::sse_encode(self.curvature_matching, serializer);
        <bool>::sse_encode(self.energy_dissipation, serializer);
        <bool>::sse_encode(self.braking_efficiency, serializer);
        <bool>::sse_encode(self.throttle_analysis, serializer);
        <bool>::sse_encode(self.brake_pressure, serializer);
    }
}

impl SseEncode for crate::api::coaching_api::AnalyzerInfo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <bool>::sse_encode(self.enabled, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::types::BrakingState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_braking, serializer);
        <f32>::sse_encode(self.braking_g, serializer);
        <f32>::sse_encode(self.distance_since_onset, serializer);
        <Option<f32>>::sse_encode(self.reference_onset_delta_m, serializer);
    }
}

impl SseEncode for crate::types::CoachingCue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::types::CueType>::sse_encode(self.cue_type, serializer);
        <String>::sse_encode(self.message, serializer);
        <crate::types::CuePriority>::sse_encode(self.priority, serializer);
        <Option<u32>>::sse_encode(self.corner_number, serializer);
        <Option<f64>>::sse_encode(self.delta_seconds, serializer);
        <Option<f64>>::sse_encode(self.distance_delta_m, serializer);
    }
}

impl SseEncode for crate::types::Corner {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.number, serializer);
        <String>::sse_encode(self.name, serializer);
        <crate::types::LatLng>::sse_encode(self.entry, serializer);
        <crate::types::LatLng>::sse_encode(self.apex, serializer);
        <crate::types::LatLng>::sse_encode(self.exit, serializer);
    }
}

impl SseEncode for crate::types::CueConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u8>::sse_encode(self.verbosity, serializer);
        <bool>::sse_encode(self.enable_braking_cues, serializer);
        <bool>::sse_encode(self.enable_corner_speed_cues, serializer);
        <bool>::sse_encode(self.enable_delta_t_cues, serializer);
        <bool>::sse_encode(self.enable_coasting_cues, serializer);
        <bool>::sse_encode(self.enable_grip_limit_cues, serializer);
        <bool>::sse_encode(self.enable_trail_braking_cues, serializer);
        <bool>::sse_encode(self.enable_jerk_cues, serializer);
        <f64>::sse_encode(self.delta_t_threshold_s, serializer);
        <f32>::sse_encode(self.coasting_threshold, serializer);
        <f32>::sse_encode(self.over_driving_threshold, serializer);
        <f32>::sse_encode(self.braking_delta_threshold_m, serializer);
        <f32>::sse_encode(self.corner_speed_threshold_kmh, serializer);
        <f32>::sse_encode(self.per_corner_cooldown_s, serializer);
        <f32>::sse_encode(self.per_type_cooldown_s, serializer);
    }
}

impl SseEncode for crate::types::CuePriority {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::types::CuePriority::Low => 0,
                crate::types::CuePriority::Medium => 1,
                crate::types::CuePriority::High => 2,
                crate::types::CuePriority::Critical => 3,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::types::CueType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::types::CueType::Braking => 0,
                crate::types::CueType::Throttle => 1,
                crate::types::CueType::Line => 2,
                crate::types::CueType::Speed => 3,
                crate::types::CueType::SectorTime => 4,
                crate::types::CueType::LapTime => 5,
                crate::types::CueType::GForce => 6,
                crate::types::CueType::General => 7,
                crate::types::CueType::Coasting => 8,
                crate::types::CueType::TrailBraking => 9,
                crate::types::CueType::GripUtilization => 10,
                crate::types::CueType::MlBraking => 11,
                crate::types::CueType::MlThrottle => 12,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for f32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::types::FrameOutput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.track_distance_m, serializer);
        <f32>::sse_encode(self.lap_distance_pct, serializer);
        <f64>::sse_encode(self.delta_t_seconds, serializer);
        <f32>::sse_encode(self.delta_t_trend, serializer);
        <Vec<crate::types::CoachingCue>>::sse_encode(self.coaching_cues, serializer);
        <crate::types::FrictionCircleState>::sse_encode(self.friction_circle, serializer);
        <crate::types::BrakingState>::sse_encode(self.braking_state, serializer);
        <u32>::sse_encode(self.current_sector, serializer);
        <Option<f64>>::sse_encode(self.sector_delta, serializer);
        <f32>::sse_encode(self.grip_utilization, serializer);
    }
}

impl SseEncode for crate::types::FrictionCircleState {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.g_total, serializer);
        <f32>::sse_encode(self.g_max, serializer);
        <f32>::sse_encode(self.utilization, serializer);
        <bool>::sse_encode(self.is_coasting, serializer);
        <bool>::sse_encode(self.is_trail_braking, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::types::ImuBias {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.lateral_g, serializer);
        <f32>::sse_encode(self.longitudinal_g, serializer);
        <f32>::sse_encode(self.vertical_g, serializer);
        <u32>::sse_encode(self.sample_count, serializer);
    }
}

impl SseEncode for crate::api::coaching_api::ImuSample {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f32>::sse_encode(self.g_lateral, serializer);
        <f32>::sse_encode(self.g_longitudinal, serializer);
        <f32>::sse_encode(self.g_vertical, serializer);
    }
}

impl SseEncode for crate::types::LatLng {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <f64>::sse_encode(self.lat, serializer);
        <f64>::sse_encode(self.lng, serializer);
    }
}

impl SseEncode for Vec<crate::api::coaching_api::AnalyzerInfo> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::coaching_api::AnalyzerInfo>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::types::CoachingCue> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::types::CoachingCue>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::types::Corner> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::types::Corner>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::coaching_api::ImuSample> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::coaching_api::ImuSample>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::types::LatLng> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::types::LatLng>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <f32>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::types::SectorSplit> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::types::SectorSplit>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::types::TelemetryInput> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::types::TelemetryInput>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::types::CueConfig> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::types::CueConfig>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<f64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <f64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::types::ImuBias> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::types::ImuBias>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u32> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u32>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::types::SectorSplit {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.sector_number, serializer);
        <crate::types::LatLng>::sse_encode(self.point_a, serializer);
        <crate::types::LatLng>::sse_encode(self.point_b, serializer);
    }
}

impl SseEncode for crate::types::SessionConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::types::TrackConfig>::sse_encode(self.track, serializer);
        <crate::types::AnalysisConfig>::sse_encode(self.analysis, serializer);
        <bool>::sse_encode(self.use_mph, serializer);
    }
}

impl SseEncode for crate::types::TelemetryInput {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.timestamp_ms, serializer);
        <f64>::sse_encode(self.latitude, serializer);
        <f64>::sse_encode(self.longitude, serializer);
        <f32>::sse_encode(self.speed_kmh, serializer);
        <f32>::sse_encode(self.heading_deg, serializer);
        <f32>::sse_encode(self.altitude_m, serializer);
        <f32>::sse_encode(self.g_lateral, serializer);
        <f32>::sse_encode(self.g_longitudinal, serializer);
        <f32>::sse_encode(self.g_vertical, serializer);
        <u8>::sse_encode(self.satellites, serializer);
        <f32>::sse_encode(self.hdop, serializer);
    }
}

impl SseEncode for crate::types::TrackConfig {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.name, serializer);
        <crate::types::LatLng>::sse_encode(self.finish_line_a, serializer);
        <crate::types::LatLng>::sse_encode(self.finish_line_b, serializer);
        <Vec<crate::types::Corner>>::sse_encode(self.corners, serializer);
        <Vec<crate::types::SectorSplit>>::sse_encode(self.sector_splits, serializer);
        <Vec<crate::types::LatLng>>::sse_encode(self.centerline, serializer);
        <Option<f64>>::sse_encode(self.track_length_m, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
