//! Core types shared across the analysis engine.
//!
//! Proto-defined types (GpsData, Corner, SectorSplit, etc.) are generated by
//! proto2type and re-exported from `crate::generated::proto`. This file keeps
//! only the analysis-engine-specific types that have no proto equivalent.

// Re-export proto-generated types used by the engine (file-private).
// Gated behind not(frb_codegen) since the generated module is excluded
// during FRB codegen.
#[cfg(not(feature = "frb_codegen"))]
use crate::generated::proto::{
    CoachingCue as ProtoCoachingCue, CoachingCueType as ProtoCueType, Corner as ProtoCorner,
    CuePriority as ProtoCuePriority, GpsData, SectorSplit as ProtoSectorSplit, Track as ProtoTrack,
    TrackConfiguration as ProtoTrackConfiguration,
};

// ─── FFI-boundary types (Dart ↔ Rust) ────────────────────────────────────

/// Raw telemetry input — what Dart sends to Rust each frame (25 Hz).
///
/// This is a flattened version of the proto TelemetryFrame, optimized for
/// the FFI boundary (no nesting, no Option, no heap allocation).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TelemetryInput {
    pub timestamp_ms: u64,
    pub latitude: f64,
    pub longitude: f64,
    pub speed_kmh: f32,
    pub heading_deg: f32,
    pub altitude_m: f32,
    pub g_lateral: f32,
    pub g_longitudinal: f32,
    pub g_vertical: f32,
    pub satellites: u8,
    pub hdop: f32,
}

/// Complete output returned to Dart after processing one frame.
#[derive(Debug, Clone)]
pub struct FrameOutput {
    pub track_distance_m: f64,
    pub lap_distance_pct: f32,
    pub delta_t_seconds: f64,
    pub delta_t_trend: f32,
    pub coaching_cues: Vec<CoachingCue>,
    pub friction_circle: FrictionCircleState,
    pub braking_state: BrakingState,
    pub current_sector: u32,
    pub sector_delta: Option<f64>,
    pub grip_utilization: f32,
}

impl Default for FrameOutput {
    fn default() -> Self {
        Self {
            track_distance_m: 0.0,
            lap_distance_pct: 0.0,
            delta_t_seconds: 0.0,
            delta_t_trend: 0.0,
            coaching_cues: Vec::new(),
            friction_circle: FrictionCircleState::default(),
            braking_state: BrakingState::default(),
            current_sector: 0,
            sector_delta: None,
            grip_utilization: 0.0,
        }
    }
}

// ─── Coaching cue types (engine-specific superset of proto) ──────────────

/// A coaching cue to be spoken via TTS.
///
/// Uses engine-specific [CueType] which is a superset of the proto's
/// CoachingCueType (adds ML and dynamics-specific cue types).
#[derive(Debug, Clone)]
pub struct CoachingCue {
    pub cue_type: CueType,
    pub message: String,
    pub priority: CuePriority,
    pub corner_number: Option<u32>,
    pub delta_seconds: Option<f64>,
    pub distance_delta_m: Option<f64>,
}

/// Type of coaching cue — superset of proto CoachingCueType.
///
/// Extends the proto enum with analysis-engine-specific cue types
/// (Coasting, TrailBraking, GripUtilization, ML variants).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CueType {
    // Proto-defined variants
    Braking,
    Throttle,
    Line,
    Speed,
    SectorTime,
    LapTime,
    GForce,
    General,

    // Engine-specific variants (no proto equivalent yet)
    Coasting,
    TrailBraking,
    GripUtilization,
    MlBraking,
    MlThrottle,
}

#[cfg(not(feature = "frb_codegen"))]
impl From<ProtoCueType> for CueType {
    fn from(proto: ProtoCueType) -> Self {
        match proto {
            ProtoCueType::Braking => CueType::Braking,
            ProtoCueType::Throttle => CueType::Throttle,
            ProtoCueType::Line => CueType::Line,
            ProtoCueType::Speed => CueType::Speed,
            ProtoCueType::SectorTime => CueType::SectorTime,
            ProtoCueType::LapTime => CueType::LapTime,
            ProtoCueType::GForce => CueType::GForce,
            ProtoCueType::General | ProtoCueType::Unspecified => CueType::General,
        }
    }
}

/// Priority level for coaching cues.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum CuePriority {
    Low = 0,
    Medium = 1,
    High = 2,
    Critical = 3,
}

#[cfg(not(feature = "frb_codegen"))]
impl From<ProtoCuePriority> for CuePriority {
    fn from(proto: ProtoCuePriority) -> Self {
        match proto {
            ProtoCuePriority::Low => CuePriority::Low,
            ProtoCuePriority::Medium => CuePriority::Medium,
            ProtoCuePriority::High => CuePriority::High,
            ProtoCuePriority::Critical => CuePriority::Critical,
            ProtoCuePriority::Unspecified => CuePriority::Low,
        }
    }
}

// ─── Analysis engine types (no proto equivalent) ─────────────────────────

/// Real-time friction circle state.
#[derive(Debug, Clone, Copy, Default)]
pub struct FrictionCircleState {
    pub g_total: f32,
    pub g_max: f32,
    pub utilization: f32,
    pub is_coasting: bool,
    pub is_trail_braking: bool,
}

/// Current braking state.
#[derive(Debug, Clone, Copy, Default)]
pub struct BrakingState {
    pub is_braking: bool,
    pub braking_g: f32,
    pub distance_since_onset: f32,
    pub reference_onset_delta_m: Option<f32>,
}

/// Configuration for which analyzers are enabled.
#[derive(Debug, Clone)]
pub struct AnalysisConfig {
    // Distance methods
    pub speed_integrated_distance: bool,
    pub centerline_projection: bool,

    // Timing
    pub sector_timer: bool,
    pub delta_t: bool,

    // Braking
    pub braking_g_onset: bool,
    pub corner_speed: bool,
    pub trail_braking: bool,
    pub jerk_analysis: bool,
    pub speed_derivative: bool,

    // Dynamics
    pub friction_circle: bool,
    pub combined_g: bool,

    // Stubs (future)
    pub heading_matching: bool,
    pub curvature_matching: bool,
    pub energy_dissipation: bool,
    pub braking_efficiency: bool,

    // OBD-II (future)
    pub throttle_analysis: bool,
    pub brake_pressure: bool,
}

impl Default for AnalysisConfig {
    fn default() -> Self {
        Self {
            // Enabled by default
            speed_integrated_distance: true,
            sector_timer: true,
            delta_t: true,
            braking_g_onset: true,
            corner_speed: true,
            friction_circle: true,

            // Disabled by default
            centerline_projection: false,
            trail_braking: false,
            jerk_analysis: false,
            speed_derivative: false,
            combined_g: false,
            heading_matching: false,
            curvature_matching: false,
            energy_dissipation: false,
            braking_efficiency: false,
            throttle_analysis: false,
            brake_pressure: false,
        }
    }
}

/// A GPS coordinate pair — lightweight, stack-allocated.
///
/// Uses f64 for precision in distance calculations.
/// For serializable GPS data, see proto-generated [GpsData].
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LatLng {
    pub lat: f64,
    pub lng: f64,
}

#[cfg(not(feature = "frb_codegen"))]
impl From<&GpsData> for LatLng {
    fn from(gps: &GpsData) -> Self {
        Self {
            lat: gps.latitude,
            lng: gps.longitude,
        }
    }
}

/// A corner/turn definition from the track configuration.
#[derive(Debug, Clone)]
pub struct Corner {
    pub number: u32,
    pub name: String,
    pub entry: LatLng,
    pub apex: LatLng,
    pub exit: LatLng,
}

/// A sector split line (two GPS points defining a line across the track).
#[derive(Debug, Clone, Copy)]
pub struct SectorSplit {
    pub sector_number: u32,
    pub point_a: LatLng,
    pub point_b: LatLng,
}

/// Track configuration provided at session start.
#[derive(Debug, Clone)]
pub struct TrackConfig {
    pub name: String,
    pub finish_line_a: LatLng,
    pub finish_line_b: LatLng,
    pub corners: Vec<Corner>,
    pub sector_splits: Vec<SectorSplit>,
    pub centerline: Vec<LatLng>,
    pub track_length_m: Option<f64>,
}

/// Session configuration for initializing the analysis engine.
#[derive(Debug, Clone)]
pub struct SessionConfig {
    pub track: TrackConfig,
    pub analysis: AnalysisConfig,
    pub use_mph: bool,
}

/// IMU bias correction from stationary calibration.
#[derive(Debug, Clone, Copy, Default)]
pub struct ImuBias {
    pub lateral_g: f32,
    pub longitudinal_g: f32,
    pub vertical_g: f32,
    pub sample_count: u32,
}

/// User-configurable coaching cue settings, passed from Dart via FFI.
///
/// Covers verbosity level, per-cue-type enable/disable toggles,
/// detection thresholds, and cooldown durations.
#[derive(Debug, Clone)]
pub struct CueConfig {
    // ── Verbosity ────────────────────────────────────────────────
    /// 0 = Low (Critical + High only), 1 = Medium, 2 = High (default, all)
    pub verbosity: u8,

    // ── Per-cue-type toggles ─────────────────────────────────────
    pub enable_braking_cues: bool,
    pub enable_corner_speed_cues: bool,
    pub enable_delta_t_cues: bool,
    pub enable_coasting_cues: bool,
    pub enable_grip_limit_cues: bool,
    pub enable_trail_braking_cues: bool,
    pub enable_jerk_cues: bool,

    // ── CueEngine thresholds ─────────────────────────────────────
    pub delta_t_threshold_s: f64,
    pub coasting_threshold: f32,
    pub over_driving_threshold: f32,
    pub braking_delta_threshold_m: f32,

    // ── Analyzer thresholds ──────────────────────────────────────
    pub corner_speed_threshold_kmh: f32,

    // ── Cooldowns (in seconds — converted to frames internally) ──
    pub per_corner_cooldown_s: f32,
    pub per_type_cooldown_s: f32,
}

impl Default for CueConfig {
    fn default() -> Self {
        Self {
            verbosity: 2,
            enable_braking_cues: true,
            enable_corner_speed_cues: true,
            enable_delta_t_cues: true,
            enable_coasting_cues: true,
            enable_grip_limit_cues: true,
            enable_trail_braking_cues: false,
            enable_jerk_cues: false,
            delta_t_threshold_s: 0.5,
            coasting_threshold: 0.15,
            over_driving_threshold: 0.95,
            braking_delta_threshold_m: 5.0,
            corner_speed_threshold_kmh: 3.0,
            per_corner_cooldown_s: 3.0,
            per_type_cooldown_s: 1.0,
        }
    }
}

impl CueConfig {
    /// The frame rate used to convert seconds to frame counts.
    const FRAME_RATE: f32 = 25.0;

    /// Convert per_corner_cooldown_s to frames.
    pub fn per_corner_cooldown_frames(&self) -> u32 {
        (self.per_corner_cooldown_s * Self::FRAME_RATE) as u32
    }

    /// Convert per_type_cooldown_s to frames.
    pub fn per_type_cooldown_frames(&self) -> u32 {
        (self.per_type_cooldown_s * Self::FRAME_RATE) as u32
    }

    /// Check if a cue type is enabled by its toggle.
    pub fn is_cue_type_enabled(&self, cue_type: &CueType) -> bool {
        match cue_type {
            CueType::Braking => self.enable_braking_cues,
            CueType::Speed => self.enable_corner_speed_cues,
            CueType::LapTime | CueType::SectorTime => self.enable_delta_t_cues,
            CueType::Coasting => self.enable_coasting_cues,
            CueType::GripUtilization | CueType::GForce => self.enable_grip_limit_cues,
            CueType::TrailBraking => self.enable_trail_braking_cues,
            CueType::MlBraking | CueType::MlThrottle => self.enable_jerk_cues,
            // Always-on types
            CueType::Throttle | CueType::Line | CueType::General => true,
        }
    }

    /// Minimum priority for a cue to pass the verbosity filter.
    pub fn min_priority(&self) -> CuePriority {
        match self.verbosity {
            0 => CuePriority::High,
            1 => CuePriority::Medium,
            _ => CuePriority::Low,
        }
    }
}

// ─── Debug / diagnostic types ────────────────────────────────────────────

/// Snapshot of the CueEngine's internal state for the debug HUD.
///
/// Returned by `get_debug_state()` — called from Dart only when the
/// developer overlay is visible.
#[derive(Debug, Clone, Default)]
pub struct DebugEngineState {
    pub queue_depth: u8,
    pub max_queue_depth: u8,
    pub cues_emitted_lap: u32,
    pub cues_filtered_lap: u32,
    pub cues_emitted_session: u32,
    pub cues_filtered_session: u32,
    pub active_cooldowns: Vec<CooldownInfo>,
}

/// A single active cooldown entry for the debug HUD.
#[derive(Debug, Clone)]
pub struct CooldownInfo {
    pub cue_type: String,
    pub frames_remaining: u32,
}
