// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/coaching_api.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1255071112;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'race_coach_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ImuBias?> crateApiCoachingApiCalibrateImu({
    required List<ImuSample> samples,
  });

  Future<void> crateApiCoachingApiClearReferenceLap();

  Future<bool> crateApiCoachingApiCreateSession({
    required SessionConfig config,
    CueConfig? cueConfig,
  });

  Future<void> crateApiCoachingApiDestroySession();

  Future<String> crateApiCoachingApiGetDebugStateJson();

  Future<Float32List> crateApiCoachingApiGetMlFeatures();

  String crateApiSimpleGreet({required String name});

  Future<bool> crateApiCoachingApiHasReferenceLap();

  Future<void> crateApiSimpleInitApp();

  Future<List<AnalyzerInfo>> crateApiCoachingApiListAnalyzers();

  Future<FrameOutput> crateApiCoachingApiProcessFrame({
    required TelemetryInput input,
  });

  Future<void> crateApiCoachingApiResetLap();

  Future<void> crateApiCoachingApiSetAnalysisConfig({
    required AnalysisConfig config,
  });

  Future<void> crateApiCoachingApiSetCueConfig({required CueConfig config});

  Future<void> crateApiCoachingApiSetReferenceLap({
    required List<TelemetryInput> frames,
    required double lapTimeS,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ImuBias?> crateApiCoachingApiCalibrateImu({
    required List<ImuSample> samples,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_imu_sample(samples, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_imu_bias,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiCalibrateImuConstMeta,
        argValues: [samples],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiCalibrateImuConstMeta =>
      const TaskConstMeta(debugName: "calibrate_imu", argNames: ["samples"]);

  @override
  Future<void> crateApiCoachingApiClearReferenceLap() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiClearReferenceLapConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiClearReferenceLapConstMeta =>
      const TaskConstMeta(debugName: "clear_reference_lap", argNames: []);

  @override
  Future<bool> crateApiCoachingApiCreateSession({
    required SessionConfig config,
    CueConfig? cueConfig,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_session_config(config, serializer);
          sse_encode_opt_box_autoadd_cue_config(cueConfig, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiCreateSessionConstMeta,
        argValues: [config, cueConfig],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiCreateSessionConstMeta =>
      const TaskConstMeta(
        debugName: "create_session",
        argNames: ["config", "cueConfig"],
      );

  @override
  Future<void> crateApiCoachingApiDestroySession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiDestroySessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiDestroySessionConstMeta =>
      const TaskConstMeta(debugName: "destroy_session", argNames: []);

  @override
  Future<String> crateApiCoachingApiGetDebugStateJson() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiGetDebugStateJsonConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiGetDebugStateJsonConstMeta =>
      const TaskConstMeta(debugName: "get_debug_state_json", argNames: []);

  @override
  Future<Float32List> crateApiCoachingApiGetMlFeatures() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_f_32_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiGetMlFeaturesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiGetMlFeaturesConstMeta =>
      const TaskConstMeta(debugName: "get_ml_features", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<bool> crateApiCoachingApiHasReferenceLap() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiHasReferenceLapConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiHasReferenceLapConstMeta =>
      const TaskConstMeta(debugName: "has_reference_lap", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<AnalyzerInfo>> crateApiCoachingApiListAnalyzers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_analyzer_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiListAnalyzersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiListAnalyzersConstMeta =>
      const TaskConstMeta(debugName: "list_analyzers", argNames: []);

  @override
  Future<FrameOutput> crateApiCoachingApiProcessFrame({
    required TelemetryInput input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_telemetry_input(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frame_output,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiProcessFrameConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiProcessFrameConstMeta =>
      const TaskConstMeta(debugName: "process_frame", argNames: ["input"]);

  @override
  Future<void> crateApiCoachingApiResetLap() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiResetLapConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiResetLapConstMeta =>
      const TaskConstMeta(debugName: "reset_lap", argNames: []);

  @override
  Future<void> crateApiCoachingApiSetAnalysisConfig({
    required AnalysisConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_analysis_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiSetAnalysisConfigConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiSetAnalysisConfigConstMeta =>
      const TaskConstMeta(
        debugName: "set_analysis_config",
        argNames: ["config"],
      );

  @override
  Future<void> crateApiCoachingApiSetCueConfig({required CueConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cue_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiSetCueConfigConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiSetCueConfigConstMeta =>
      const TaskConstMeta(debugName: "set_cue_config", argNames: ["config"]);

  @override
  Future<void> crateApiCoachingApiSetReferenceLap({
    required List<TelemetryInput> frames,
    required double lapTimeS,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_telemetry_input(frames, serializer);
          sse_encode_f_64(lapTimeS, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoachingApiSetReferenceLapConstMeta,
        argValues: [frames, lapTimeS],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoachingApiSetReferenceLapConstMeta =>
      const TaskConstMeta(
        debugName: "set_reference_lap",
        argNames: ["frames", "lapTimeS"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnalysisConfig dco_decode_analysis_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return AnalysisConfig(
      speedIntegratedDistance: dco_decode_bool(arr[0]),
      centerlineProjection: dco_decode_bool(arr[1]),
      sectorTimer: dco_decode_bool(arr[2]),
      deltaT: dco_decode_bool(arr[3]),
      brakingGOnset: dco_decode_bool(arr[4]),
      cornerSpeed: dco_decode_bool(arr[5]),
      trailBraking: dco_decode_bool(arr[6]),
      jerkAnalysis: dco_decode_bool(arr[7]),
      speedDerivative: dco_decode_bool(arr[8]),
      frictionCircle: dco_decode_bool(arr[9]),
      combinedG: dco_decode_bool(arr[10]),
      headingMatching: dco_decode_bool(arr[11]),
      curvatureMatching: dco_decode_bool(arr[12]),
      energyDissipation: dco_decode_bool(arr[13]),
      brakingEfficiency: dco_decode_bool(arr[14]),
      throttleAnalysis: dco_decode_bool(arr[15]),
      brakePressure: dco_decode_bool(arr[16]),
    );
  }

  @protected
  AnalyzerInfo dco_decode_analyzer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AnalyzerInfo(
      id: dco_decode_String(arr[0]),
      enabled: dco_decode_bool(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AnalysisConfig dco_decode_box_autoadd_analysis_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_analysis_config(raw);
  }

  @protected
  CueConfig dco_decode_box_autoadd_cue_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_cue_config(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  ImuBias dco_decode_box_autoadd_imu_bias(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_imu_bias(raw);
  }

  @protected
  SessionConfig dco_decode_box_autoadd_session_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_session_config(raw);
  }

  @protected
  TelemetryInput dco_decode_box_autoadd_telemetry_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_telemetry_input(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BrakingState dco_decode_braking_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BrakingState(
      isBraking: dco_decode_bool(arr[0]),
      brakingG: dco_decode_f_32(arr[1]),
      distanceSinceOnset: dco_decode_f_32(arr[2]),
      referenceOnsetDeltaM: dco_decode_opt_box_autoadd_f_32(arr[3]),
    );
  }

  @protected
  CoachingCue dco_decode_coaching_cue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return CoachingCue(
      cueType: dco_decode_cue_type(arr[0]),
      message: dco_decode_String(arr[1]),
      priority: dco_decode_cue_priority(arr[2]),
      cornerNumber: dco_decode_opt_box_autoadd_u_32(arr[3]),
      deltaSeconds: dco_decode_opt_box_autoadd_f_64(arr[4]),
      distanceDeltaM: dco_decode_opt_box_autoadd_f_64(arr[5]),
    );
  }

  @protected
  Corner dco_decode_corner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Corner(
      number: dco_decode_u_32(arr[0]),
      name: dco_decode_String(arr[1]),
      entry: dco_decode_lat_lng(arr[2]),
      apex: dco_decode_lat_lng(arr[3]),
      exit: dco_decode_lat_lng(arr[4]),
    );
  }

  @protected
  CueConfig dco_decode_cue_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return CueConfig(
      verbosity: dco_decode_u_8(arr[0]),
      enableBrakingCues: dco_decode_bool(arr[1]),
      enableCornerSpeedCues: dco_decode_bool(arr[2]),
      enableDeltaTCues: dco_decode_bool(arr[3]),
      enableCoastingCues: dco_decode_bool(arr[4]),
      enableGripLimitCues: dco_decode_bool(arr[5]),
      enableTrailBrakingCues: dco_decode_bool(arr[6]),
      enableJerkCues: dco_decode_bool(arr[7]),
      deltaTThresholdS: dco_decode_f_64(arr[8]),
      coastingThreshold: dco_decode_f_32(arr[9]),
      overDrivingThreshold: dco_decode_f_32(arr[10]),
      brakingDeltaThresholdM: dco_decode_f_32(arr[11]),
      cornerSpeedThresholdKmh: dco_decode_f_32(arr[12]),
      perCornerCooldownS: dco_decode_f_32(arr[13]),
      perTypeCooldownS: dco_decode_f_32(arr[14]),
    );
  }

  @protected
  CuePriority dco_decode_cue_priority(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CuePriority.values[raw as int];
  }

  @protected
  CueType dco_decode_cue_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CueType.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrameOutput dco_decode_frame_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return FrameOutput(
      trackDistanceM: dco_decode_f_64(arr[0]),
      lapDistancePct: dco_decode_f_32(arr[1]),
      deltaTSeconds: dco_decode_f_64(arr[2]),
      deltaTTrend: dco_decode_f_32(arr[3]),
      coachingCues: dco_decode_list_coaching_cue(arr[4]),
      frictionCircle: dco_decode_friction_circle_state(arr[5]),
      brakingState: dco_decode_braking_state(arr[6]),
      currentSector: dco_decode_u_32(arr[7]),
      sectorDelta: dco_decode_opt_box_autoadd_f_64(arr[8]),
      gripUtilization: dco_decode_f_32(arr[9]),
    );
  }

  @protected
  FrictionCircleState dco_decode_friction_circle_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FrictionCircleState(
      gTotal: dco_decode_f_32(arr[0]),
      gMax: dco_decode_f_32(arr[1]),
      utilization: dco_decode_f_32(arr[2]),
      isCoasting: dco_decode_bool(arr[3]),
      isTrailBraking: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  ImuBias dco_decode_imu_bias(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ImuBias(
      lateralG: dco_decode_f_32(arr[0]),
      longitudinalG: dco_decode_f_32(arr[1]),
      verticalG: dco_decode_f_32(arr[2]),
      sampleCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  ImuSample dco_decode_imu_sample(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ImuSample(
      gLateral: dco_decode_f_32(arr[0]),
      gLongitudinal: dco_decode_f_32(arr[1]),
      gVertical: dco_decode_f_32(arr[2]),
    );
  }

  @protected
  LatLng dco_decode_lat_lng(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return LatLng(lat: dco_decode_f_64(arr[0]), lng: dco_decode_f_64(arr[1]));
  }

  @protected
  List<AnalyzerInfo> dco_decode_list_analyzer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_analyzer_info).toList();
  }

  @protected
  List<CoachingCue> dco_decode_list_coaching_cue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_coaching_cue).toList();
  }

  @protected
  List<Corner> dco_decode_list_corner(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_corner).toList();
  }

  @protected
  List<ImuSample> dco_decode_list_imu_sample(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_imu_sample).toList();
  }

  @protected
  List<LatLng> dco_decode_list_lat_lng(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lat_lng).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SectorSplit> dco_decode_list_sector_split(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sector_split).toList();
  }

  @protected
  List<TelemetryInput> dco_decode_list_telemetry_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_telemetry_input).toList();
  }

  @protected
  CueConfig? dco_decode_opt_box_autoadd_cue_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_cue_config(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  ImuBias? dco_decode_opt_box_autoadd_imu_bias(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_imu_bias(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  SectorSplit dco_decode_sector_split(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SectorSplit(
      sectorNumber: dco_decode_u_32(arr[0]),
      pointA: dco_decode_lat_lng(arr[1]),
      pointB: dco_decode_lat_lng(arr[2]),
    );
  }

  @protected
  SessionConfig dco_decode_session_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionConfig(
      track: dco_decode_track_config(arr[0]),
      analysis: dco_decode_analysis_config(arr[1]),
      useMph: dco_decode_bool(arr[2]),
    );
  }

  @protected
  TelemetryInput dco_decode_telemetry_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return TelemetryInput(
      timestampMs: dco_decode_u_64(arr[0]),
      latitude: dco_decode_f_64(arr[1]),
      longitude: dco_decode_f_64(arr[2]),
      speedKmh: dco_decode_f_32(arr[3]),
      headingDeg: dco_decode_f_32(arr[4]),
      altitudeM: dco_decode_f_32(arr[5]),
      gLateral: dco_decode_f_32(arr[6]),
      gLongitudinal: dco_decode_f_32(arr[7]),
      gVertical: dco_decode_f_32(arr[8]),
      satellites: dco_decode_u_8(arr[9]),
      hdop: dco_decode_f_32(arr[10]),
    );
  }

  @protected
  TrackConfig dco_decode_track_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TrackConfig(
      name: dco_decode_String(arr[0]),
      finishLineA: dco_decode_lat_lng(arr[1]),
      finishLineB: dco_decode_lat_lng(arr[2]),
      corners: dco_decode_list_corner(arr[3]),
      sectorSplits: dco_decode_list_sector_split(arr[4]),
      centerline: dco_decode_list_lat_lng(arr[5]),
      trackLengthM: dco_decode_opt_box_autoadd_f_64(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnalysisConfig sse_decode_analysis_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_speedIntegratedDistance = sse_decode_bool(deserializer);
    var var_centerlineProjection = sse_decode_bool(deserializer);
    var var_sectorTimer = sse_decode_bool(deserializer);
    var var_deltaT = sse_decode_bool(deserializer);
    var var_brakingGOnset = sse_decode_bool(deserializer);
    var var_cornerSpeed = sse_decode_bool(deserializer);
    var var_trailBraking = sse_decode_bool(deserializer);
    var var_jerkAnalysis = sse_decode_bool(deserializer);
    var var_speedDerivative = sse_decode_bool(deserializer);
    var var_frictionCircle = sse_decode_bool(deserializer);
    var var_combinedG = sse_decode_bool(deserializer);
    var var_headingMatching = sse_decode_bool(deserializer);
    var var_curvatureMatching = sse_decode_bool(deserializer);
    var var_energyDissipation = sse_decode_bool(deserializer);
    var var_brakingEfficiency = sse_decode_bool(deserializer);
    var var_throttleAnalysis = sse_decode_bool(deserializer);
    var var_brakePressure = sse_decode_bool(deserializer);
    return AnalysisConfig(
      speedIntegratedDistance: var_speedIntegratedDistance,
      centerlineProjection: var_centerlineProjection,
      sectorTimer: var_sectorTimer,
      deltaT: var_deltaT,
      brakingGOnset: var_brakingGOnset,
      cornerSpeed: var_cornerSpeed,
      trailBraking: var_trailBraking,
      jerkAnalysis: var_jerkAnalysis,
      speedDerivative: var_speedDerivative,
      frictionCircle: var_frictionCircle,
      combinedG: var_combinedG,
      headingMatching: var_headingMatching,
      curvatureMatching: var_curvatureMatching,
      energyDissipation: var_energyDissipation,
      brakingEfficiency: var_brakingEfficiency,
      throttleAnalysis: var_throttleAnalysis,
      brakePressure: var_brakePressure,
    );
  }

  @protected
  AnalyzerInfo sse_decode_analyzer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_enabled = sse_decode_bool(deserializer);
    return AnalyzerInfo(id: var_id, enabled: var_enabled);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AnalysisConfig sse_decode_box_autoadd_analysis_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_analysis_config(deserializer));
  }

  @protected
  CueConfig sse_decode_box_autoadd_cue_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_cue_config(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  ImuBias sse_decode_box_autoadd_imu_bias(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_imu_bias(deserializer));
  }

  @protected
  SessionConfig sse_decode_box_autoadd_session_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_session_config(deserializer));
  }

  @protected
  TelemetryInput sse_decode_box_autoadd_telemetry_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_telemetry_input(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BrakingState sse_decode_braking_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isBraking = sse_decode_bool(deserializer);
    var var_brakingG = sse_decode_f_32(deserializer);
    var var_distanceSinceOnset = sse_decode_f_32(deserializer);
    var var_referenceOnsetDeltaM = sse_decode_opt_box_autoadd_f_32(
      deserializer,
    );
    return BrakingState(
      isBraking: var_isBraking,
      brakingG: var_brakingG,
      distanceSinceOnset: var_distanceSinceOnset,
      referenceOnsetDeltaM: var_referenceOnsetDeltaM,
    );
  }

  @protected
  CoachingCue sse_decode_coaching_cue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cueType = sse_decode_cue_type(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_priority = sse_decode_cue_priority(deserializer);
    var var_cornerNumber = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_deltaSeconds = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_distanceDeltaM = sse_decode_opt_box_autoadd_f_64(deserializer);
    return CoachingCue(
      cueType: var_cueType,
      message: var_message,
      priority: var_priority,
      cornerNumber: var_cornerNumber,
      deltaSeconds: var_deltaSeconds,
      distanceDeltaM: var_distanceDeltaM,
    );
  }

  @protected
  Corner sse_decode_corner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_number = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_entry = sse_decode_lat_lng(deserializer);
    var var_apex = sse_decode_lat_lng(deserializer);
    var var_exit = sse_decode_lat_lng(deserializer);
    return Corner(
      number: var_number,
      name: var_name,
      entry: var_entry,
      apex: var_apex,
      exit: var_exit,
    );
  }

  @protected
  CueConfig sse_decode_cue_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_verbosity = sse_decode_u_8(deserializer);
    var var_enableBrakingCues = sse_decode_bool(deserializer);
    var var_enableCornerSpeedCues = sse_decode_bool(deserializer);
    var var_enableDeltaTCues = sse_decode_bool(deserializer);
    var var_enableCoastingCues = sse_decode_bool(deserializer);
    var var_enableGripLimitCues = sse_decode_bool(deserializer);
    var var_enableTrailBrakingCues = sse_decode_bool(deserializer);
    var var_enableJerkCues = sse_decode_bool(deserializer);
    var var_deltaTThresholdS = sse_decode_f_64(deserializer);
    var var_coastingThreshold = sse_decode_f_32(deserializer);
    var var_overDrivingThreshold = sse_decode_f_32(deserializer);
    var var_brakingDeltaThresholdM = sse_decode_f_32(deserializer);
    var var_cornerSpeedThresholdKmh = sse_decode_f_32(deserializer);
    var var_perCornerCooldownS = sse_decode_f_32(deserializer);
    var var_perTypeCooldownS = sse_decode_f_32(deserializer);
    return CueConfig(
      verbosity: var_verbosity,
      enableBrakingCues: var_enableBrakingCues,
      enableCornerSpeedCues: var_enableCornerSpeedCues,
      enableDeltaTCues: var_enableDeltaTCues,
      enableCoastingCues: var_enableCoastingCues,
      enableGripLimitCues: var_enableGripLimitCues,
      enableTrailBrakingCues: var_enableTrailBrakingCues,
      enableJerkCues: var_enableJerkCues,
      deltaTThresholdS: var_deltaTThresholdS,
      coastingThreshold: var_coastingThreshold,
      overDrivingThreshold: var_overDrivingThreshold,
      brakingDeltaThresholdM: var_brakingDeltaThresholdM,
      cornerSpeedThresholdKmh: var_cornerSpeedThresholdKmh,
      perCornerCooldownS: var_perCornerCooldownS,
      perTypeCooldownS: var_perTypeCooldownS,
    );
  }

  @protected
  CuePriority sse_decode_cue_priority(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CuePriority.values[inner];
  }

  @protected
  CueType sse_decode_cue_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CueType.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FrameOutput sse_decode_frame_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_trackDistanceM = sse_decode_f_64(deserializer);
    var var_lapDistancePct = sse_decode_f_32(deserializer);
    var var_deltaTSeconds = sse_decode_f_64(deserializer);
    var var_deltaTTrend = sse_decode_f_32(deserializer);
    var var_coachingCues = sse_decode_list_coaching_cue(deserializer);
    var var_frictionCircle = sse_decode_friction_circle_state(deserializer);
    var var_brakingState = sse_decode_braking_state(deserializer);
    var var_currentSector = sse_decode_u_32(deserializer);
    var var_sectorDelta = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_gripUtilization = sse_decode_f_32(deserializer);
    return FrameOutput(
      trackDistanceM: var_trackDistanceM,
      lapDistancePct: var_lapDistancePct,
      deltaTSeconds: var_deltaTSeconds,
      deltaTTrend: var_deltaTTrend,
      coachingCues: var_coachingCues,
      frictionCircle: var_frictionCircle,
      brakingState: var_brakingState,
      currentSector: var_currentSector,
      sectorDelta: var_sectorDelta,
      gripUtilization: var_gripUtilization,
    );
  }

  @protected
  FrictionCircleState sse_decode_friction_circle_state(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gTotal = sse_decode_f_32(deserializer);
    var var_gMax = sse_decode_f_32(deserializer);
    var var_utilization = sse_decode_f_32(deserializer);
    var var_isCoasting = sse_decode_bool(deserializer);
    var var_isTrailBraking = sse_decode_bool(deserializer);
    return FrictionCircleState(
      gTotal: var_gTotal,
      gMax: var_gMax,
      utilization: var_utilization,
      isCoasting: var_isCoasting,
      isTrailBraking: var_isTrailBraking,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  ImuBias sse_decode_imu_bias(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lateralG = sse_decode_f_32(deserializer);
    var var_longitudinalG = sse_decode_f_32(deserializer);
    var var_verticalG = sse_decode_f_32(deserializer);
    var var_sampleCount = sse_decode_u_32(deserializer);
    return ImuBias(
      lateralG: var_lateralG,
      longitudinalG: var_longitudinalG,
      verticalG: var_verticalG,
      sampleCount: var_sampleCount,
    );
  }

  @protected
  ImuSample sse_decode_imu_sample(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_gLateral = sse_decode_f_32(deserializer);
    var var_gLongitudinal = sse_decode_f_32(deserializer);
    var var_gVertical = sse_decode_f_32(deserializer);
    return ImuSample(
      gLateral: var_gLateral,
      gLongitudinal: var_gLongitudinal,
      gVertical: var_gVertical,
    );
  }

  @protected
  LatLng sse_decode_lat_lng(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lat = sse_decode_f_64(deserializer);
    var var_lng = sse_decode_f_64(deserializer);
    return LatLng(lat: var_lat, lng: var_lng);
  }

  @protected
  List<AnalyzerInfo> sse_decode_list_analyzer_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnalyzerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_analyzer_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<CoachingCue> sse_decode_list_coaching_cue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CoachingCue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_coaching_cue(deserializer));
    }
    return ans_;
  }

  @protected
  List<Corner> sse_decode_list_corner(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Corner>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_corner(deserializer));
    }
    return ans_;
  }

  @protected
  List<ImuSample> sse_decode_list_imu_sample(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ImuSample>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_imu_sample(deserializer));
    }
    return ans_;
  }

  @protected
  List<LatLng> sse_decode_list_lat_lng(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LatLng>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lat_lng(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SectorSplit> sse_decode_list_sector_split(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SectorSplit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sector_split(deserializer));
    }
    return ans_;
  }

  @protected
  List<TelemetryInput> sse_decode_list_telemetry_input(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TelemetryInput>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_telemetry_input(deserializer));
    }
    return ans_;
  }

  @protected
  CueConfig? sse_decode_opt_box_autoadd_cue_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_cue_config(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ImuBias? sse_decode_opt_box_autoadd_imu_bias(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_imu_bias(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  SectorSplit sse_decode_sector_split(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sectorNumber = sse_decode_u_32(deserializer);
    var var_pointA = sse_decode_lat_lng(deserializer);
    var var_pointB = sse_decode_lat_lng(deserializer);
    return SectorSplit(
      sectorNumber: var_sectorNumber,
      pointA: var_pointA,
      pointB: var_pointB,
    );
  }

  @protected
  SessionConfig sse_decode_session_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_track = sse_decode_track_config(deserializer);
    var var_analysis = sse_decode_analysis_config(deserializer);
    var var_useMph = sse_decode_bool(deserializer);
    return SessionConfig(
      track: var_track,
      analysis: var_analysis,
      useMph: var_useMph,
    );
  }

  @protected
  TelemetryInput sse_decode_telemetry_input(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_latitude = sse_decode_f_64(deserializer);
    var var_longitude = sse_decode_f_64(deserializer);
    var var_speedKmh = sse_decode_f_32(deserializer);
    var var_headingDeg = sse_decode_f_32(deserializer);
    var var_altitudeM = sse_decode_f_32(deserializer);
    var var_gLateral = sse_decode_f_32(deserializer);
    var var_gLongitudinal = sse_decode_f_32(deserializer);
    var var_gVertical = sse_decode_f_32(deserializer);
    var var_satellites = sse_decode_u_8(deserializer);
    var var_hdop = sse_decode_f_32(deserializer);
    return TelemetryInput(
      timestampMs: var_timestampMs,
      latitude: var_latitude,
      longitude: var_longitude,
      speedKmh: var_speedKmh,
      headingDeg: var_headingDeg,
      altitudeM: var_altitudeM,
      gLateral: var_gLateral,
      gLongitudinal: var_gLongitudinal,
      gVertical: var_gVertical,
      satellites: var_satellites,
      hdop: var_hdop,
    );
  }

  @protected
  TrackConfig sse_decode_track_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_finishLineA = sse_decode_lat_lng(deserializer);
    var var_finishLineB = sse_decode_lat_lng(deserializer);
    var var_corners = sse_decode_list_corner(deserializer);
    var var_sectorSplits = sse_decode_list_sector_split(deserializer);
    var var_centerline = sse_decode_list_lat_lng(deserializer);
    var var_trackLengthM = sse_decode_opt_box_autoadd_f_64(deserializer);
    return TrackConfig(
      name: var_name,
      finishLineA: var_finishLineA,
      finishLineB: var_finishLineB,
      corners: var_corners,
      sectorSplits: var_sectorSplits,
      centerline: var_centerline,
      trackLengthM: var_trackLengthM,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_analysis_config(
    AnalysisConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.speedIntegratedDistance, serializer);
    sse_encode_bool(self.centerlineProjection, serializer);
    sse_encode_bool(self.sectorTimer, serializer);
    sse_encode_bool(self.deltaT, serializer);
    sse_encode_bool(self.brakingGOnset, serializer);
    sse_encode_bool(self.cornerSpeed, serializer);
    sse_encode_bool(self.trailBraking, serializer);
    sse_encode_bool(self.jerkAnalysis, serializer);
    sse_encode_bool(self.speedDerivative, serializer);
    sse_encode_bool(self.frictionCircle, serializer);
    sse_encode_bool(self.combinedG, serializer);
    sse_encode_bool(self.headingMatching, serializer);
    sse_encode_bool(self.curvatureMatching, serializer);
    sse_encode_bool(self.energyDissipation, serializer);
    sse_encode_bool(self.brakingEfficiency, serializer);
    sse_encode_bool(self.throttleAnalysis, serializer);
    sse_encode_bool(self.brakePressure, serializer);
  }

  @protected
  void sse_encode_analyzer_info(AnalyzerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_bool(self.enabled, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_analysis_config(
    AnalysisConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_analysis_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_cue_config(
    CueConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_cue_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_imu_bias(ImuBias self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_imu_bias(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_session_config(
    SessionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_session_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_telemetry_input(
    TelemetryInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_telemetry_input(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_braking_state(BrakingState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isBraking, serializer);
    sse_encode_f_32(self.brakingG, serializer);
    sse_encode_f_32(self.distanceSinceOnset, serializer);
    sse_encode_opt_box_autoadd_f_32(self.referenceOnsetDeltaM, serializer);
  }

  @protected
  void sse_encode_coaching_cue(CoachingCue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_cue_type(self.cueType, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_cue_priority(self.priority, serializer);
    sse_encode_opt_box_autoadd_u_32(self.cornerNumber, serializer);
    sse_encode_opt_box_autoadd_f_64(self.deltaSeconds, serializer);
    sse_encode_opt_box_autoadd_f_64(self.distanceDeltaM, serializer);
  }

  @protected
  void sse_encode_corner(Corner self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.number, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_lat_lng(self.entry, serializer);
    sse_encode_lat_lng(self.apex, serializer);
    sse_encode_lat_lng(self.exit, serializer);
  }

  @protected
  void sse_encode_cue_config(CueConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.verbosity, serializer);
    sse_encode_bool(self.enableBrakingCues, serializer);
    sse_encode_bool(self.enableCornerSpeedCues, serializer);
    sse_encode_bool(self.enableDeltaTCues, serializer);
    sse_encode_bool(self.enableCoastingCues, serializer);
    sse_encode_bool(self.enableGripLimitCues, serializer);
    sse_encode_bool(self.enableTrailBrakingCues, serializer);
    sse_encode_bool(self.enableJerkCues, serializer);
    sse_encode_f_64(self.deltaTThresholdS, serializer);
    sse_encode_f_32(self.coastingThreshold, serializer);
    sse_encode_f_32(self.overDrivingThreshold, serializer);
    sse_encode_f_32(self.brakingDeltaThresholdM, serializer);
    sse_encode_f_32(self.cornerSpeedThresholdKmh, serializer);
    sse_encode_f_32(self.perCornerCooldownS, serializer);
    sse_encode_f_32(self.perTypeCooldownS, serializer);
  }

  @protected
  void sse_encode_cue_priority(CuePriority self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_cue_type(CueType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_frame_output(FrameOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.trackDistanceM, serializer);
    sse_encode_f_32(self.lapDistancePct, serializer);
    sse_encode_f_64(self.deltaTSeconds, serializer);
    sse_encode_f_32(self.deltaTTrend, serializer);
    sse_encode_list_coaching_cue(self.coachingCues, serializer);
    sse_encode_friction_circle_state(self.frictionCircle, serializer);
    sse_encode_braking_state(self.brakingState, serializer);
    sse_encode_u_32(self.currentSector, serializer);
    sse_encode_opt_box_autoadd_f_64(self.sectorDelta, serializer);
    sse_encode_f_32(self.gripUtilization, serializer);
  }

  @protected
  void sse_encode_friction_circle_state(
    FrictionCircleState self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.gTotal, serializer);
    sse_encode_f_32(self.gMax, serializer);
    sse_encode_f_32(self.utilization, serializer);
    sse_encode_bool(self.isCoasting, serializer);
    sse_encode_bool(self.isTrailBraking, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_imu_bias(ImuBias self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.lateralG, serializer);
    sse_encode_f_32(self.longitudinalG, serializer);
    sse_encode_f_32(self.verticalG, serializer);
    sse_encode_u_32(self.sampleCount, serializer);
  }

  @protected
  void sse_encode_imu_sample(ImuSample self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.gLateral, serializer);
    sse_encode_f_32(self.gLongitudinal, serializer);
    sse_encode_f_32(self.gVertical, serializer);
  }

  @protected
  void sse_encode_lat_lng(LatLng self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.lat, serializer);
    sse_encode_f_64(self.lng, serializer);
  }

  @protected
  void sse_encode_list_analyzer_info(
    List<AnalyzerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_analyzer_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_coaching_cue(
    List<CoachingCue> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_coaching_cue(item, serializer);
    }
  }

  @protected
  void sse_encode_list_corner(List<Corner> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_corner(item, serializer);
    }
  }

  @protected
  void sse_encode_list_imu_sample(
    List<ImuSample> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_imu_sample(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lat_lng(List<LatLng> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lat_lng(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_sector_split(
    List<SectorSplit> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sector_split(item, serializer);
    }
  }

  @protected
  void sse_encode_list_telemetry_input(
    List<TelemetryInput> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_telemetry_input(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_cue_config(
    CueConfig? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_cue_config(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_imu_bias(
    ImuBias? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_imu_bias(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_sector_split(SectorSplit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.sectorNumber, serializer);
    sse_encode_lat_lng(self.pointA, serializer);
    sse_encode_lat_lng(self.pointB, serializer);
  }

  @protected
  void sse_encode_session_config(SessionConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_track_config(self.track, serializer);
    sse_encode_analysis_config(self.analysis, serializer);
    sse_encode_bool(self.useMph, serializer);
  }

  @protected
  void sse_encode_telemetry_input(
    TelemetryInput self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_f_64(self.latitude, serializer);
    sse_encode_f_64(self.longitude, serializer);
    sse_encode_f_32(self.speedKmh, serializer);
    sse_encode_f_32(self.headingDeg, serializer);
    sse_encode_f_32(self.altitudeM, serializer);
    sse_encode_f_32(self.gLateral, serializer);
    sse_encode_f_32(self.gLongitudinal, serializer);
    sse_encode_f_32(self.gVertical, serializer);
    sse_encode_u_8(self.satellites, serializer);
    sse_encode_f_32(self.hdop, serializer);
  }

  @protected
  void sse_encode_track_config(TrackConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_lat_lng(self.finishLineA, serializer);
    sse_encode_lat_lng(self.finishLineB, serializer);
    sse_encode_list_corner(self.corners, serializer);
    sse_encode_list_sector_split(self.sectorSplits, serializer);
    sse_encode_list_lat_lng(self.centerline, serializer);
    sse_encode_opt_box_autoadd_f_64(self.trackLengthM, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
