// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/coaching_api.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnalysisConfig dco_decode_analysis_config(dynamic raw);

  @protected
  AnalyzerInfo dco_decode_analyzer_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AnalysisConfig dco_decode_box_autoadd_analysis_config(dynamic raw);

  @protected
  CueConfig dco_decode_box_autoadd_cue_config(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  ImuBias dco_decode_box_autoadd_imu_bias(dynamic raw);

  @protected
  SessionConfig dco_decode_box_autoadd_session_config(dynamic raw);

  @protected
  TelemetryInput dco_decode_box_autoadd_telemetry_input(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BrakingState dco_decode_braking_state(dynamic raw);

  @protected
  CoachingCue dco_decode_coaching_cue(dynamic raw);

  @protected
  Corner dco_decode_corner(dynamic raw);

  @protected
  CueConfig dco_decode_cue_config(dynamic raw);

  @protected
  CuePriority dco_decode_cue_priority(dynamic raw);

  @protected
  CueType dco_decode_cue_type(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FrameOutput dco_decode_frame_output(dynamic raw);

  @protected
  FrictionCircleState dco_decode_friction_circle_state(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  ImuBias dco_decode_imu_bias(dynamic raw);

  @protected
  ImuSample dco_decode_imu_sample(dynamic raw);

  @protected
  LatLng dco_decode_lat_lng(dynamic raw);

  @protected
  List<AnalyzerInfo> dco_decode_list_analyzer_info(dynamic raw);

  @protected
  List<CoachingCue> dco_decode_list_coaching_cue(dynamic raw);

  @protected
  List<Corner> dco_decode_list_corner(dynamic raw);

  @protected
  List<ImuSample> dco_decode_list_imu_sample(dynamic raw);

  @protected
  List<LatLng> dco_decode_list_lat_lng(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SectorSplit> dco_decode_list_sector_split(dynamic raw);

  @protected
  List<TelemetryInput> dco_decode_list_telemetry_input(dynamic raw);

  @protected
  CueConfig? dco_decode_opt_box_autoadd_cue_config(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  ImuBias? dco_decode_opt_box_autoadd_imu_bias(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  SectorSplit dco_decode_sector_split(dynamic raw);

  @protected
  SessionConfig dco_decode_session_config(dynamic raw);

  @protected
  TelemetryInput dco_decode_telemetry_input(dynamic raw);

  @protected
  TrackConfig dco_decode_track_config(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnalysisConfig sse_decode_analysis_config(SseDeserializer deserializer);

  @protected
  AnalyzerInfo sse_decode_analyzer_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AnalysisConfig sse_decode_box_autoadd_analysis_config(
    SseDeserializer deserializer,
  );

  @protected
  CueConfig sse_decode_box_autoadd_cue_config(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ImuBias sse_decode_box_autoadd_imu_bias(SseDeserializer deserializer);

  @protected
  SessionConfig sse_decode_box_autoadd_session_config(
    SseDeserializer deserializer,
  );

  @protected
  TelemetryInput sse_decode_box_autoadd_telemetry_input(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BrakingState sse_decode_braking_state(SseDeserializer deserializer);

  @protected
  CoachingCue sse_decode_coaching_cue(SseDeserializer deserializer);

  @protected
  Corner sse_decode_corner(SseDeserializer deserializer);

  @protected
  CueConfig sse_decode_cue_config(SseDeserializer deserializer);

  @protected
  CuePriority sse_decode_cue_priority(SseDeserializer deserializer);

  @protected
  CueType sse_decode_cue_type(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FrameOutput sse_decode_frame_output(SseDeserializer deserializer);

  @protected
  FrictionCircleState sse_decode_friction_circle_state(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  ImuBias sse_decode_imu_bias(SseDeserializer deserializer);

  @protected
  ImuSample sse_decode_imu_sample(SseDeserializer deserializer);

  @protected
  LatLng sse_decode_lat_lng(SseDeserializer deserializer);

  @protected
  List<AnalyzerInfo> sse_decode_list_analyzer_info(
    SseDeserializer deserializer,
  );

  @protected
  List<CoachingCue> sse_decode_list_coaching_cue(SseDeserializer deserializer);

  @protected
  List<Corner> sse_decode_list_corner(SseDeserializer deserializer);

  @protected
  List<ImuSample> sse_decode_list_imu_sample(SseDeserializer deserializer);

  @protected
  List<LatLng> sse_decode_list_lat_lng(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SectorSplit> sse_decode_list_sector_split(SseDeserializer deserializer);

  @protected
  List<TelemetryInput> sse_decode_list_telemetry_input(
    SseDeserializer deserializer,
  );

  @protected
  CueConfig? sse_decode_opt_box_autoadd_cue_config(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ImuBias? sse_decode_opt_box_autoadd_imu_bias(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  SectorSplit sse_decode_sector_split(SseDeserializer deserializer);

  @protected
  SessionConfig sse_decode_session_config(SseDeserializer deserializer);

  @protected
  TelemetryInput sse_decode_telemetry_input(SseDeserializer deserializer);

  @protected
  TrackConfig sse_decode_track_config(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_analysis_config(
    AnalysisConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_analyzer_info(AnalyzerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_analysis_config(
    AnalysisConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_cue_config(
    CueConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_imu_bias(ImuBias self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_session_config(
    SessionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_telemetry_input(
    TelemetryInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_braking_state(BrakingState self, SseSerializer serializer);

  @protected
  void sse_encode_coaching_cue(CoachingCue self, SseSerializer serializer);

  @protected
  void sse_encode_corner(Corner self, SseSerializer serializer);

  @protected
  void sse_encode_cue_config(CueConfig self, SseSerializer serializer);

  @protected
  void sse_encode_cue_priority(CuePriority self, SseSerializer serializer);

  @protected
  void sse_encode_cue_type(CueType self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_frame_output(FrameOutput self, SseSerializer serializer);

  @protected
  void sse_encode_friction_circle_state(
    FrictionCircleState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_imu_bias(ImuBias self, SseSerializer serializer);

  @protected
  void sse_encode_imu_sample(ImuSample self, SseSerializer serializer);

  @protected
  void sse_encode_lat_lng(LatLng self, SseSerializer serializer);

  @protected
  void sse_encode_list_analyzer_info(
    List<AnalyzerInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_coaching_cue(
    List<CoachingCue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_corner(List<Corner> self, SseSerializer serializer);

  @protected
  void sse_encode_list_imu_sample(
    List<ImuSample> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lat_lng(List<LatLng> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sector_split(
    List<SectorSplit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_telemetry_input(
    List<TelemetryInput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_cue_config(
    CueConfig? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_imu_bias(
    ImuBias? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_sector_split(SectorSplit self, SseSerializer serializer);

  @protected
  void sse_encode_session_config(SessionConfig self, SseSerializer serializer);

  @protected
  void sse_encode_telemetry_input(
    TelemetryInput self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_config(TrackConfig self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
