// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Configuration for which analyzers are enabled.
class AnalysisConfig {
  final bool speedIntegratedDistance;
  final bool centerlineProjection;
  final bool sectorTimer;
  final bool deltaT;
  final bool brakingGOnset;
  final bool cornerSpeed;
  final bool trailBraking;
  final bool jerkAnalysis;
  final bool speedDerivative;
  final bool frictionCircle;
  final bool combinedG;
  final bool headingMatching;
  final bool curvatureMatching;
  final bool energyDissipation;
  final bool brakingEfficiency;
  final bool throttleAnalysis;
  final bool brakePressure;

  const AnalysisConfig({
    required this.speedIntegratedDistance,
    required this.centerlineProjection,
    required this.sectorTimer,
    required this.deltaT,
    required this.brakingGOnset,
    required this.cornerSpeed,
    required this.trailBraking,
    required this.jerkAnalysis,
    required this.speedDerivative,
    required this.frictionCircle,
    required this.combinedG,
    required this.headingMatching,
    required this.curvatureMatching,
    required this.energyDissipation,
    required this.brakingEfficiency,
    required this.throttleAnalysis,
    required this.brakePressure,
  });

  @override
  int get hashCode =>
      speedIntegratedDistance.hashCode ^
      centerlineProjection.hashCode ^
      sectorTimer.hashCode ^
      deltaT.hashCode ^
      brakingGOnset.hashCode ^
      cornerSpeed.hashCode ^
      trailBraking.hashCode ^
      jerkAnalysis.hashCode ^
      speedDerivative.hashCode ^
      frictionCircle.hashCode ^
      combinedG.hashCode ^
      headingMatching.hashCode ^
      curvatureMatching.hashCode ^
      energyDissipation.hashCode ^
      brakingEfficiency.hashCode ^
      throttleAnalysis.hashCode ^
      brakePressure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalysisConfig &&
          runtimeType == other.runtimeType &&
          speedIntegratedDistance == other.speedIntegratedDistance &&
          centerlineProjection == other.centerlineProjection &&
          sectorTimer == other.sectorTimer &&
          deltaT == other.deltaT &&
          brakingGOnset == other.brakingGOnset &&
          cornerSpeed == other.cornerSpeed &&
          trailBraking == other.trailBraking &&
          jerkAnalysis == other.jerkAnalysis &&
          speedDerivative == other.speedDerivative &&
          frictionCircle == other.frictionCircle &&
          combinedG == other.combinedG &&
          headingMatching == other.headingMatching &&
          curvatureMatching == other.curvatureMatching &&
          energyDissipation == other.energyDissipation &&
          brakingEfficiency == other.brakingEfficiency &&
          throttleAnalysis == other.throttleAnalysis &&
          brakePressure == other.brakePressure;
}

/// Current braking state.
class BrakingState {
  final bool isBraking;
  final double brakingG;
  final double distanceSinceOnset;
  final double? referenceOnsetDeltaM;

  const BrakingState({
    required this.isBraking,
    required this.brakingG,
    required this.distanceSinceOnset,
    this.referenceOnsetDeltaM,
  });

  @override
  int get hashCode =>
      isBraking.hashCode ^
      brakingG.hashCode ^
      distanceSinceOnset.hashCode ^
      referenceOnsetDeltaM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BrakingState &&
          runtimeType == other.runtimeType &&
          isBraking == other.isBraking &&
          brakingG == other.brakingG &&
          distanceSinceOnset == other.distanceSinceOnset &&
          referenceOnsetDeltaM == other.referenceOnsetDeltaM;
}

/// A coaching cue to be spoken via TTS.
///
/// Uses engine-specific [CueType] which is a superset of the proto's
/// CoachingCueType (adds ML and dynamics-specific cue types).
class CoachingCue {
  final CueType cueType;
  final String message;
  final CuePriority priority;
  final int? cornerNumber;
  final double? deltaSeconds;
  final double? distanceDeltaM;

  const CoachingCue({
    required this.cueType,
    required this.message,
    required this.priority,
    this.cornerNumber,
    this.deltaSeconds,
    this.distanceDeltaM,
  });

  @override
  int get hashCode =>
      cueType.hashCode ^
      message.hashCode ^
      priority.hashCode ^
      cornerNumber.hashCode ^
      deltaSeconds.hashCode ^
      distanceDeltaM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoachingCue &&
          runtimeType == other.runtimeType &&
          cueType == other.cueType &&
          message == other.message &&
          priority == other.priority &&
          cornerNumber == other.cornerNumber &&
          deltaSeconds == other.deltaSeconds &&
          distanceDeltaM == other.distanceDeltaM;
}

/// A corner/turn definition from the track configuration.
class Corner {
  final int number;
  final String name;
  final LatLng entry;
  final LatLng apex;
  final LatLng exit;

  const Corner({
    required this.number,
    required this.name,
    required this.entry,
    required this.apex,
    required this.exit,
  });

  @override
  int get hashCode =>
      number.hashCode ^
      name.hashCode ^
      entry.hashCode ^
      apex.hashCode ^
      exit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Corner &&
          runtimeType == other.runtimeType &&
          number == other.number &&
          name == other.name &&
          entry == other.entry &&
          apex == other.apex &&
          exit == other.exit;
}

/// User-configurable coaching cue settings, passed from Dart via FFI.
///
/// Covers verbosity level, per-cue-type enable/disable toggles,
/// detection thresholds, and cooldown durations.
class CueConfig {
  /// 0 = Low (Critical + High only), 1 = Medium, 2 = High (default, all)
  final int verbosity;
  final bool enableBrakingCues;
  final bool enableCornerSpeedCues;
  final bool enableDeltaTCues;
  final bool enableCoastingCues;
  final bool enableGripLimitCues;
  final bool enableTrailBrakingCues;
  final bool enableJerkCues;
  final double deltaTThresholdS;
  final double coastingThreshold;
  final double overDrivingThreshold;
  final double brakingDeltaThresholdM;
  final double cornerSpeedThresholdKmh;
  final double perCornerCooldownS;
  final double perTypeCooldownS;

  const CueConfig({
    required this.verbosity,
    required this.enableBrakingCues,
    required this.enableCornerSpeedCues,
    required this.enableDeltaTCues,
    required this.enableCoastingCues,
    required this.enableGripLimitCues,
    required this.enableTrailBrakingCues,
    required this.enableJerkCues,
    required this.deltaTThresholdS,
    required this.coastingThreshold,
    required this.overDrivingThreshold,
    required this.brakingDeltaThresholdM,
    required this.cornerSpeedThresholdKmh,
    required this.perCornerCooldownS,
    required this.perTypeCooldownS,
  });

  @override
  int get hashCode =>
      verbosity.hashCode ^
      enableBrakingCues.hashCode ^
      enableCornerSpeedCues.hashCode ^
      enableDeltaTCues.hashCode ^
      enableCoastingCues.hashCode ^
      enableGripLimitCues.hashCode ^
      enableTrailBrakingCues.hashCode ^
      enableJerkCues.hashCode ^
      deltaTThresholdS.hashCode ^
      coastingThreshold.hashCode ^
      overDrivingThreshold.hashCode ^
      brakingDeltaThresholdM.hashCode ^
      cornerSpeedThresholdKmh.hashCode ^
      perCornerCooldownS.hashCode ^
      perTypeCooldownS.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueConfig &&
          runtimeType == other.runtimeType &&
          verbosity == other.verbosity &&
          enableBrakingCues == other.enableBrakingCues &&
          enableCornerSpeedCues == other.enableCornerSpeedCues &&
          enableDeltaTCues == other.enableDeltaTCues &&
          enableCoastingCues == other.enableCoastingCues &&
          enableGripLimitCues == other.enableGripLimitCues &&
          enableTrailBrakingCues == other.enableTrailBrakingCues &&
          enableJerkCues == other.enableJerkCues &&
          deltaTThresholdS == other.deltaTThresholdS &&
          coastingThreshold == other.coastingThreshold &&
          overDrivingThreshold == other.overDrivingThreshold &&
          brakingDeltaThresholdM == other.brakingDeltaThresholdM &&
          cornerSpeedThresholdKmh == other.cornerSpeedThresholdKmh &&
          perCornerCooldownS == other.perCornerCooldownS &&
          perTypeCooldownS == other.perTypeCooldownS;
}

/// Priority level for coaching cues.
enum CuePriority { low, medium, high, critical }

/// Type of coaching cue — superset of proto CoachingCueType.
///
/// Extends the proto enum with analysis-engine-specific cue types
/// (Coasting, TrailBraking, GripUtilization, ML variants).
enum CueType {
  braking,
  throttle,
  line,
  speed,
  sectorTime,
  lapTime,
  gForce,
  general,
  coasting,
  trailBraking,
  gripUtilization,
  mlBraking,
  mlThrottle,
}

/// Complete output returned to Dart after processing one frame.
class FrameOutput {
  final double trackDistanceM;
  final double lapDistancePct;
  final double deltaTSeconds;
  final double deltaTTrend;
  final List<CoachingCue> coachingCues;
  final FrictionCircleState frictionCircle;
  final BrakingState brakingState;
  final int currentSector;
  final double? sectorDelta;
  final double gripUtilization;

  const FrameOutput({
    required this.trackDistanceM,
    required this.lapDistancePct,
    required this.deltaTSeconds,
    required this.deltaTTrend,
    required this.coachingCues,
    required this.frictionCircle,
    required this.brakingState,
    required this.currentSector,
    this.sectorDelta,
    required this.gripUtilization,
  });

  @override
  int get hashCode =>
      trackDistanceM.hashCode ^
      lapDistancePct.hashCode ^
      deltaTSeconds.hashCode ^
      deltaTTrend.hashCode ^
      coachingCues.hashCode ^
      frictionCircle.hashCode ^
      brakingState.hashCode ^
      currentSector.hashCode ^
      sectorDelta.hashCode ^
      gripUtilization.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameOutput &&
          runtimeType == other.runtimeType &&
          trackDistanceM == other.trackDistanceM &&
          lapDistancePct == other.lapDistancePct &&
          deltaTSeconds == other.deltaTSeconds &&
          deltaTTrend == other.deltaTTrend &&
          coachingCues == other.coachingCues &&
          frictionCircle == other.frictionCircle &&
          brakingState == other.brakingState &&
          currentSector == other.currentSector &&
          sectorDelta == other.sectorDelta &&
          gripUtilization == other.gripUtilization;
}

/// Real-time friction circle state.
class FrictionCircleState {
  final double gTotal;
  final double gMax;
  final double utilization;
  final bool isCoasting;
  final bool isTrailBraking;

  const FrictionCircleState({
    required this.gTotal,
    required this.gMax,
    required this.utilization,
    required this.isCoasting,
    required this.isTrailBraking,
  });

  @override
  int get hashCode =>
      gTotal.hashCode ^
      gMax.hashCode ^
      utilization.hashCode ^
      isCoasting.hashCode ^
      isTrailBraking.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrictionCircleState &&
          runtimeType == other.runtimeType &&
          gTotal == other.gTotal &&
          gMax == other.gMax &&
          utilization == other.utilization &&
          isCoasting == other.isCoasting &&
          isTrailBraking == other.isTrailBraking;
}

/// IMU bias correction from stationary calibration.
class ImuBias {
  final double lateralG;
  final double longitudinalG;
  final double verticalG;
  final int sampleCount;

  const ImuBias({
    required this.lateralG,
    required this.longitudinalG,
    required this.verticalG,
    required this.sampleCount,
  });

  @override
  int get hashCode =>
      lateralG.hashCode ^
      longitudinalG.hashCode ^
      verticalG.hashCode ^
      sampleCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImuBias &&
          runtimeType == other.runtimeType &&
          lateralG == other.lateralG &&
          longitudinalG == other.longitudinalG &&
          verticalG == other.verticalG &&
          sampleCount == other.sampleCount;
}

/// A GPS coordinate pair — lightweight, stack-allocated.
///
/// Uses f64 for precision in distance calculations.
/// For serializable GPS data, see proto-generated [GpsData].
class LatLng {
  final double lat;
  final double lng;

  const LatLng({required this.lat, required this.lng});

  @override
  int get hashCode => lat.hashCode ^ lng.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LatLng &&
          runtimeType == other.runtimeType &&
          lat == other.lat &&
          lng == other.lng;
}

/// A sector split line (two GPS points defining a line across the track).
class SectorSplit {
  final int sectorNumber;
  final LatLng pointA;
  final LatLng pointB;

  const SectorSplit({
    required this.sectorNumber,
    required this.pointA,
    required this.pointB,
  });

  @override
  int get hashCode => sectorNumber.hashCode ^ pointA.hashCode ^ pointB.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SectorSplit &&
          runtimeType == other.runtimeType &&
          sectorNumber == other.sectorNumber &&
          pointA == other.pointA &&
          pointB == other.pointB;
}

/// Session configuration for initializing the analysis engine.
class SessionConfig {
  final TrackConfig track;
  final AnalysisConfig analysis;
  final bool useMph;

  const SessionConfig({
    required this.track,
    required this.analysis,
    required this.useMph,
  });

  @override
  int get hashCode => track.hashCode ^ analysis.hashCode ^ useMph.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionConfig &&
          runtimeType == other.runtimeType &&
          track == other.track &&
          analysis == other.analysis &&
          useMph == other.useMph;
}

/// Raw telemetry input — what Dart sends to Rust each frame (25 Hz).
///
/// This is a flattened version of the proto TelemetryFrame, optimized for
/// the FFI boundary (no nesting, no Option, no heap allocation).
class TelemetryInput {
  final BigInt timestampMs;
  final double latitude;
  final double longitude;
  final double speedKmh;
  final double headingDeg;
  final double altitudeM;
  final double gLateral;
  final double gLongitudinal;
  final double gVertical;
  final int satellites;
  final double hdop;

  const TelemetryInput({
    required this.timestampMs,
    required this.latitude,
    required this.longitude,
    required this.speedKmh,
    required this.headingDeg,
    required this.altitudeM,
    required this.gLateral,
    required this.gLongitudinal,
    required this.gVertical,
    required this.satellites,
    required this.hdop,
  });

  @override
  int get hashCode =>
      timestampMs.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      speedKmh.hashCode ^
      headingDeg.hashCode ^
      altitudeM.hashCode ^
      gLateral.hashCode ^
      gLongitudinal.hashCode ^
      gVertical.hashCode ^
      satellites.hashCode ^
      hdop.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelemetryInput &&
          runtimeType == other.runtimeType &&
          timestampMs == other.timestampMs &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          speedKmh == other.speedKmh &&
          headingDeg == other.headingDeg &&
          altitudeM == other.altitudeM &&
          gLateral == other.gLateral &&
          gLongitudinal == other.gLongitudinal &&
          gVertical == other.gVertical &&
          satellites == other.satellites &&
          hdop == other.hdop;
}

/// Track configuration provided at session start.
class TrackConfig {
  final String name;
  final LatLng finishLineA;
  final LatLng finishLineB;
  final List<Corner> corners;
  final List<SectorSplit> sectorSplits;
  final List<LatLng> centerline;
  final double? trackLengthM;

  const TrackConfig({
    required this.name,
    required this.finishLineA,
    required this.finishLineB,
    required this.corners,
    required this.sectorSplits,
    required this.centerline,
    this.trackLengthM,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      finishLineA.hashCode ^
      finishLineB.hashCode ^
      corners.hashCode ^
      sectorSplits.hashCode ^
      centerline.hashCode ^
      trackLengthM.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackConfig &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          finishLineA == other.finishLineA &&
          finishLineB == other.finishLineB &&
          corners == other.corners &&
          sectorSplits == other.sectorSplits &&
          centerline == other.centerline &&
          trackLengthM == other.trackLengthM;
}
