// This is a CI stub for firebase_options.dart.
// The real file is generated by `flutterfire configure` and is gitignored.
// This stub satisfies `flutter analyze` in CI where Firebase is not configured.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // CI stub — will never run in production.
    return const FirebaseOptions(
      apiKey: 'ci-stub',
      appId: 'ci-stub',
      messagingSenderId: 'ci-stub',
      projectId: 'ci-stub',
    );
  }
}
