// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Session`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Create a new analysis session with the given configuration.
///
/// Call this once at session start. Registers all analyzers and
/// auto-configures based on available data.
Future<bool> createSession({
  required SessionConfig config,
  CueConfig? cueConfig,
}) => RustLib.instance.api.crateApiCoachingApiCreateSession(
  config: config,
  cueConfig: cueConfig,
);

/// Destroy the current session and free resources.
Future<void> destroySession() =>
    RustLib.instance.api.crateApiCoachingApiDestroySession();

/// Update the coaching cue configuration at runtime.
///
/// Adjusts verbosity, cue-type toggles, thresholds, and cooldowns
/// without interrupting the active session.
Future<void> setCueConfig({required CueConfig config}) =>
    RustLib.instance.api.crateApiCoachingApiSetCueConfig(config: config);

/// Process one telemetry frame and return analysis results.
///
/// This is the hot path — called 25 times per second. Must complete
/// well within the 40ms frame budget (typically <100μs).
Future<FrameOutput> processFrame({required TelemetryInput input}) =>
    RustLib.instance.api.crateApiCoachingApiProcessFrame(input: input);

/// Load a reference lap from raw telemetry frames.
///
/// Frames must be in chronological order. The engine indexes them by
/// speed-integrated distance for O(log n) lookup during process_frame().
Future<void> setReferenceLap({
  required List<TelemetryInput> frames,
  required double lapTimeS,
}) => RustLib.instance.api.crateApiCoachingApiSetReferenceLap(
  frames: frames,
  lapTimeS: lapTimeS,
);

/// Clear the loaded reference lap.
Future<void> clearReferenceLap() =>
    RustLib.instance.api.crateApiCoachingApiClearReferenceLap();

/// Check if a reference lap is loaded.
Future<bool> hasReferenceLap() =>
    RustLib.instance.api.crateApiCoachingApiHasReferenceLap();

/// Update the analysis configuration (enable/disable individual analyzers).
Future<void> setAnalysisConfig({required AnalysisConfig config}) =>
    RustLib.instance.api.crateApiCoachingApiSetAnalysisConfig(config: config);

/// Get the list of all registered analyzers and their enabled state.
Future<List<AnalyzerInfo>> listAnalyzers() =>
    RustLib.instance.api.crateApiCoachingApiListAnalyzers();

/// Run IMU bias calibration from stationary samples.
///
/// Collects the provided samples, computes the average bias, and
/// applies it to the current session. Returns the computed bias.
Future<ImuBias?> calibrateImu({required List<ImuSample> samples}) =>
    RustLib.instance.api.crateApiCoachingApiCalibrateImu(samples: samples);

/// Reset the lap (distance back to zero, reset analyzers, keep reference).
Future<void> resetLap() => RustLib.instance.api.crateApiCoachingApiResetLap();

/// Get the current ML feature vector (if the window is full).
///
/// Returns a flat Vec<f32> of features, or empty if not enough frames yet.
Future<Float32List> getMlFeatures() =>
    RustLib.instance.api.crateApiCoachingApiGetMlFeatures();

/// Info about a registered analyzer (returned by list_analyzers).
class AnalyzerInfo {
  final String id;
  final bool enabled;

  const AnalyzerInfo({required this.id, required this.enabled});

  @override
  int get hashCode => id.hashCode ^ enabled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnalyzerInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          enabled == other.enabled;
}

/// Raw IMU sample for calibration.
class ImuSample {
  final double gLateral;
  final double gLongitudinal;
  final double gVertical;

  const ImuSample({
    required this.gLateral,
    required this.gLongitudinal,
    required this.gVertical,
  });

  @override
  int get hashCode =>
      gLateral.hashCode ^ gLongitudinal.hashCode ^ gVertical.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImuSample &&
          runtimeType == other.runtimeType &&
          gLateral == other.gLateral &&
          gLongitudinal == other.gLongitudinal &&
          gVertical == other.gVertical;
}
